extern long long supercop_cpucycles_ticks_amd64_tsc_setup(void);
extern long long supercop_cpucycles_ticks_amd64_tsc(void);

extern void supercop_cpucycles_ticks_amd64_tsc_close(void);

extern long long supercop_cpucycles_ticks_amd64_tscasm_setup(void);
extern long long supercop_cpucycles_ticks_amd64_tscasm(void);

extern void supercop_cpucycles_ticks_amd64_tscasm_close(void);

extern long long supercop_cpucycles_ticks_default_perfevent_setup(void);
extern long long supercop_cpucycles_ticks_default_perfevent(void);

extern void supercop_cpucycles_ticks_default_perfevent_close(void);

extern long long supercop_cpucycles_ticks_default_mach_setup(void);
extern long long supercop_cpucycles_ticks_default_mach(void);

extern void supercop_cpucycles_ticks_default_mach_close(void);

extern long long supercop_cpucycles_ticks_default_monotonic_setup(void);
extern long long supercop_cpucycles_ticks_default_monotonic(void);

extern void supercop_cpucycles_ticks_default_monotonic_close(void);

extern long long supercop_cpucycles_ticks_default_gettimeofday_setup(void);
extern long long supercop_cpucycles_ticks_default_gettimeofday(void);

extern void supercop_cpucycles_ticks_default_gettimeofday_close(void);

extern long long supercop_cpucycles_ticks_default_zero_setup(void);
extern long long supercop_cpucycles_ticks_default_zero(void);

extern void supercop_cpucycles_ticks_default_zero_close(void);

