/* AUTO-GENERATED by keccak_gen.py — do not edit. */
/* Separate-call Keccak round, RC from buf slot. 110 triads. */
#define KECCAK_SC_TRIADS 110
#define KECCAK_SC_BUFLEN 608
#define KECCAK_SC_BASE_LANE 15
#define KECCAK_SC_RC_LANE 600
