/* AUTO-GENERATED by keccak_gen.py — do not edit. */
/* Keccak-f[1600] full 24-round permutation, looped. 112 triads. */
/* loop_top = U7c64 (after 25-triad prologue). */
#define KECCAK_PERM_TRIADS 112
#define KECCAK_BUFLEN 56
#define KECCAK_BASE_LANE 16
#define KECCAK_COUNTER_LANE 30
#define KECCAK_RCTAB_LANE 32
