/* Autogenerated: '/home/sabrina/CryptOpt/dist/data/fiat-bridge/solinas_reduction' --lang C --inline-internal --internal-static --use-value-barrier curve25519_solinas 64 '2^255 - 19' square */
/* curve description: curve25519_solinas */
/* machine_wordsize = 64 (from "64") */
/* requested operations: square */
/* s-c = 2^255 - [(1, 19)] (from "2^255 - 19") */
/*  */
/* Computed values: */
/*  */

#include <stdint.h>
typedef unsigned char fiat_curve25519_solinas_uint1;
typedef signed char fiat_curve25519_solinas_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_CURVE25519_SOLINAS_FIAT_EXTENSION __extension__
#  define FIAT_CURVE25519_SOLINAS_FIAT_INLINE __inline__
#else
#  define FIAT_CURVE25519_SOLINAS_FIAT_EXTENSION
#  define FIAT_CURVE25519_SOLINAS_FIAT_INLINE
#endif

FIAT_CURVE25519_SOLINAS_FIAT_EXTENSION typedef signed __int128 fiat_curve25519_solinas_int128;
FIAT_CURVE25519_SOLINAS_FIAT_EXTENSION typedef unsigned __int128 fiat_curve25519_solinas_uint128;

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif

#if !defined(FIAT_CURVE25519_SOLINAS_NO_ASM) && (defined(__GNUC__) || defined(__clang__))
static __inline__ uint64_t fiat_curve25519_solinas_value_barrier_u64(uint64_t a) {
  __asm__("" : "+r"(a) : /* no inputs */);
  return a;
}
#else
#  define fiat_curve25519_solinas_value_barrier_u64(x) (x)
#endif


/*
 * The function fiat_curve25519_solinas_addcarryx_u64 is an addition with carry.
 *
 * Postconditions:
 *   out1 = (arg1 + arg2 + arg3) mod 2^64
 *   out2 = ⌊(arg1 + arg2 + arg3) / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0x1]
 */
static FIAT_CURVE25519_SOLINAS_FIAT_INLINE void fiat_curve25519_solinas_addcarryx_u64(uint64_t* out1, fiat_curve25519_solinas_uint1* out2, fiat_curve25519_solinas_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_curve25519_solinas_uint128 x1;
  uint64_t x2;
  fiat_curve25519_solinas_uint1 x3;
  x1 = ((arg1 + (fiat_curve25519_solinas_uint128)arg2) + arg3);
  x2 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  x3 = (fiat_curve25519_solinas_uint1)(x1 >> 64);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_curve25519_solinas_subborrowx_u64 is a subtraction with borrow.
 *
 * Postconditions:
 *   out1 = (-arg1 + arg2 + -arg3) mod 2^64
 *   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0x1]
 */
static FIAT_CURVE25519_SOLINAS_FIAT_INLINE void fiat_curve25519_solinas_subborrowx_u64(uint64_t* out1, fiat_curve25519_solinas_uint1* out2, fiat_curve25519_solinas_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_curve25519_solinas_int128 x1;
  fiat_curve25519_solinas_int1 x2;
  uint64_t x3;
  x1 = ((arg2 - (fiat_curve25519_solinas_int128)arg1) - arg3);
  x2 = (fiat_curve25519_solinas_int1)(x1 >> 64);
  x3 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  *out1 = x3;
  *out2 = (fiat_curve25519_solinas_uint1)(0x0 - x2);
}

/*
 * The function fiat_curve25519_solinas_mulx_u64 is a multiplication, returning the full double-width result.
 *
 * Postconditions:
 *   out1 = (arg1 * arg2) mod 2^64
 *   out2 = ⌊arg1 * arg2 / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffffffffffff]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0xffffffffffffffff]
 */
static FIAT_CURVE25519_SOLINAS_FIAT_INLINE void fiat_curve25519_solinas_mulx_u64(uint64_t* out1, uint64_t* out2, uint64_t arg1, uint64_t arg2) {
  fiat_curve25519_solinas_uint128 x1;
  uint64_t x2;
  uint64_t x3;
  x1 = ((fiat_curve25519_solinas_uint128)arg1 * arg2);
  x2 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  x3 = (uint64_t)(x1 >> 64);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_curve25519_solinas_cmovznz_u64 is a single-word conditional move.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 */
static FIAT_CURVE25519_SOLINAS_FIAT_INLINE void fiat_curve25519_solinas_cmovznz_u64(uint64_t* out1, fiat_curve25519_solinas_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_curve25519_solinas_uint1 x1;
  uint64_t x2;
  uint64_t x3;
  x1 = (!(!arg1));
  x2 = ((fiat_curve25519_solinas_int1)(0x0 - x1) & UINT64_C(0xffffffffffffffff));
  x3 = ((fiat_curve25519_solinas_value_barrier_u64(x2) & arg3) | (fiat_curve25519_solinas_value_barrier_u64((~x2)) & arg2));
  *out1 = x3;
}

/*
 * The function fiat_curve25519_solinas_square squares a field element.
 *
 * Postconditions:
 *   eval out1 mod 57896044618658097711785492504343953926634992332820282019728792003956564819949 = (eval arg1 * eval arg1) mod 57896044618658097711785492504343953926634992332820282019728792003956564819949
 *
 * Input Bounds:
 *   arg1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 * Output Bounds:
 *   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
 */
void fiat_curve25519_solinas_square(uint64_t out1[4], const uint64_t arg1[4]) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  fiat_curve25519_solinas_uint1 x12;
  uint64_t x13;
  fiat_curve25519_solinas_uint1 x14;
  uint64_t x15;
  fiat_curve25519_solinas_uint1 x16;
  uint64_t x17;
  fiat_curve25519_solinas_uint1 x18;
  uint64_t x19;
  uint64_t x20;
  uint64_t x21;
  uint64_t x22;
  fiat_curve25519_solinas_uint1 x23;
  uint64_t x24;
  fiat_curve25519_solinas_uint1 x25;
  uint64_t x26;
  fiat_curve25519_solinas_uint1 x27;
  uint64_t x28;
  fiat_curve25519_solinas_uint1 x29;
  uint64_t x30;
  fiat_curve25519_solinas_uint1 x31;
  uint64_t x32;
  fiat_curve25519_solinas_uint1 x33;
  uint64_t x34;
  fiat_curve25519_solinas_uint1 x35;
  uint64_t x36;
  fiat_curve25519_solinas_uint1 x37;
  uint64_t x38;
  fiat_curve25519_solinas_uint1 x39;
  uint64_t x40;
  fiat_curve25519_solinas_uint1 x41;
  uint64_t x42;
  uint64_t x43;
  uint64_t x44;
  uint64_t x45;
  uint64_t x46;
  uint64_t x47;
  uint64_t x48;
  uint64_t x49;
  uint64_t x50;
  uint64_t x51;
  fiat_curve25519_solinas_uint1 x52;
  uint64_t x53;
  fiat_curve25519_solinas_uint1 x54;
  uint64_t x55;
  fiat_curve25519_solinas_uint1 x56;
  uint64_t x57;
  fiat_curve25519_solinas_uint1 x58;
  uint64_t x59;
  fiat_curve25519_solinas_uint1 x60;
  uint64_t x61;
  fiat_curve25519_solinas_uint1 x62;
  uint64_t x63;
  fiat_curve25519_solinas_uint1 x64;
  uint64_t x65;
  uint64_t x66;
  uint64_t x67;
  uint64_t x68;
  uint64_t x69;
  uint64_t x70;
  uint64_t x71;
  uint64_t x72;
  uint64_t x73;
  fiat_curve25519_solinas_uint1 x74;
  uint64_t x75;
  fiat_curve25519_solinas_uint1 x76;
  uint64_t x77;
  fiat_curve25519_solinas_uint1 x78;
  uint64_t x79;
  uint64_t x80;
  fiat_curve25519_solinas_uint1 x81;
  uint64_t x82;
  fiat_curve25519_solinas_uint1 x83;
  uint64_t x84;
  fiat_curve25519_solinas_uint1 x85;
  uint64_t x86;
  fiat_curve25519_solinas_uint1 x87;
  uint64_t x88;
  uint64_t x89;
  uint64_t x90;
  uint64_t x91;
  fiat_curve25519_solinas_uint1 x92;
  uint64_t x93;
  fiat_curve25519_solinas_uint1 x94;
  uint64_t x95;
  fiat_curve25519_solinas_uint1 x96;
  uint64_t x97;
  fiat_curve25519_solinas_uint1 x98;
  uint64_t x99;
  uint64_t x100;
  fiat_curve25519_solinas_uint1 x101;
  fiat_curve25519_solinas_mulx_u64(&x1, &x2, (arg1[0]), (arg1[3]));
  fiat_curve25519_solinas_mulx_u64(&x3, &x4, (arg1[0]), (arg1[2]));
  fiat_curve25519_solinas_mulx_u64(&x5, &x6, (arg1[0]), (arg1[1]));
  fiat_curve25519_solinas_mulx_u64(&x7, &x8, (arg1[3]), (arg1[2]));
  fiat_curve25519_solinas_mulx_u64(&x9, &x10, (arg1[3]), (arg1[1]));
  fiat_curve25519_solinas_addcarryx_u64(&x11, &x12, 0x0, x6, x3);
  fiat_curve25519_solinas_addcarryx_u64(&x13, &x14, x12, x4, x1);
  fiat_curve25519_solinas_addcarryx_u64(&x15, &x16, x14, x2, x9);
  fiat_curve25519_solinas_addcarryx_u64(&x17, &x18, x16, x10, x7);
  x19 = (x18 + x8);
  fiat_curve25519_solinas_mulx_u64(&x20, &x21, (arg1[1]), (arg1[2]));
  fiat_curve25519_solinas_addcarryx_u64(&x22, &x23, 0x0, x13, x20);
  fiat_curve25519_solinas_addcarryx_u64(&x24, &x25, x23, x15, x21);
  fiat_curve25519_solinas_addcarryx_u64(&x26, &x27, x25, x17, 0x0);
  fiat_curve25519_solinas_addcarryx_u64(&x28, &x29, x27, x19, 0x0);
  fiat_curve25519_solinas_addcarryx_u64(&x30, &x31, 0x0, x5, x5);
  fiat_curve25519_solinas_addcarryx_u64(&x32, &x33, x31, x11, x11);
  fiat_curve25519_solinas_addcarryx_u64(&x34, &x35, x33, x22, x22);
  fiat_curve25519_solinas_addcarryx_u64(&x36, &x37, x35, x24, x24);
  fiat_curve25519_solinas_addcarryx_u64(&x38, &x39, x37, x26, x26);
  fiat_curve25519_solinas_addcarryx_u64(&x40, &x41, x39, x28, x28);
  x42 = (((uint64_t)x41 + x29) + (uint64_t)x29);
  fiat_curve25519_solinas_mulx_u64(&x43, &x44, (arg1[3]), (arg1[3]));
  fiat_curve25519_solinas_mulx_u64(&x45, &x46, (arg1[2]), (arg1[2]));
  fiat_curve25519_solinas_mulx_u64(&x47, &x48, (arg1[1]), (arg1[1]));
  fiat_curve25519_solinas_mulx_u64(&x49, &x50, (arg1[0]), (arg1[0]));
  fiat_curve25519_solinas_addcarryx_u64(&x51, &x52, 0x0, x30, x50);
  fiat_curve25519_solinas_addcarryx_u64(&x53, &x54, x52, x32, x47);
  fiat_curve25519_solinas_addcarryx_u64(&x55, &x56, x54, x34, x48);
  fiat_curve25519_solinas_addcarryx_u64(&x57, &x58, x56, x36, x45);
  fiat_curve25519_solinas_addcarryx_u64(&x59, &x60, x58, x38, x46);
  fiat_curve25519_solinas_addcarryx_u64(&x61, &x62, x60, x40, x43);
  fiat_curve25519_solinas_addcarryx_u64(&x63, &x64, x62, x42, x44);
  fiat_curve25519_solinas_mulx_u64(&x65, &x66, UINT8_C(0x26), x63);
  fiat_curve25519_solinas_mulx_u64(&x67, &x68, UINT8_C(0x26), x61);
  fiat_curve25519_solinas_mulx_u64(&x69, &x70, UINT8_C(0x26), x59);
  fiat_curve25519_solinas_mulx_u64(&x71, &x72, UINT8_C(0x26), x57);
  fiat_curve25519_solinas_addcarryx_u64(&x73, &x74, 0x0, x51, x69);
  fiat_curve25519_solinas_addcarryx_u64(&x75, &x76, x74, x53, x67);
  fiat_curve25519_solinas_addcarryx_u64(&x77, &x78, x76, x55, x65);
  x79 = (x78 + x66);
  fiat_curve25519_solinas_addcarryx_u64(&x80, &x81, 0x0, x49, x71);
  fiat_curve25519_solinas_addcarryx_u64(&x82, &x83, x81, x73, x72);
  fiat_curve25519_solinas_addcarryx_u64(&x84, &x85, x83, x75, x70);
  fiat_curve25519_solinas_addcarryx_u64(&x86, &x87, x85, x77, x68);
  x88 = (x87 + x79);
  fiat_curve25519_solinas_mulx_u64(&x89, &x90, UINT8_C(0x26), x88);
  fiat_curve25519_solinas_addcarryx_u64(&x91, &x92, 0x0, x80, x89);
  fiat_curve25519_solinas_addcarryx_u64(&x93, &x94, x92, x82, 0x0);
  fiat_curve25519_solinas_addcarryx_u64(&x95, &x96, x94, x84, 0x0);
  fiat_curve25519_solinas_addcarryx_u64(&x97, &x98, x96, x86, 0x0);
  fiat_curve25519_solinas_cmovznz_u64(&x99, x98, 0x0, UINT8_C(0x26));
  fiat_curve25519_solinas_addcarryx_u64(&x100, &x101, 0x0, x99, x91);
  out1[0] = x100;
  out1[1] = x93;
  out1[2] = x95;
  out1[3] = x97;
}
