/* Autogenerated: '/home/sabrina/CryptOpt/dist/data/fiat-bridge/unsaturated_solinas' --lang C --inline-internal --internal-static --use-value-barrier curve25519 64 5 '2^255 - 19' carry_square */
/* curve description: curve25519 */
/* machine_wordsize = 64 (from "64") */
/* requested operations: carry_square */
/* n = 5 (from "5") */
/* s-c = 2^255 - [(1, 19)] (from "2^255 - 19") */
/* tight_bounds_multiplier = 1 (from "") */
/*  */
/* Computed values: */
/*   carry_chain = [0, 1, 2, 3, 4, 0, 1] */
/*   eval z = z[0] + (z[1] << 51) + (z[2] << 102) + (z[3] << 153) + (z[4] << 204) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) */
/*   balance = [0xfffffffffffda, 0xffffffffffffe, 0xffffffffffffe, 0xffffffffffffe, 0xffffffffffffe] */

#include <stdint.h>
typedef unsigned char fiat_curve25519_uint1;
typedef signed char fiat_curve25519_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_CURVE25519_FIAT_EXTENSION __extension__
#  define FIAT_CURVE25519_FIAT_INLINE __inline__
#else
#  define FIAT_CURVE25519_FIAT_EXTENSION
#  define FIAT_CURVE25519_FIAT_INLINE
#endif

FIAT_CURVE25519_FIAT_EXTENSION typedef signed __int128 fiat_curve25519_int128;
FIAT_CURVE25519_FIAT_EXTENSION typedef unsigned __int128 fiat_curve25519_uint128;

/* The type fiat_curve25519_loose_field_element is a field element with loose bounds. */
/* Bounds: [[0x0 ~> 0x18000000000000], [0x0 ~> 0x18000000000000], [0x0 ~> 0x18000000000000], [0x0 ~> 0x18000000000000], [0x0 ~> 0x18000000000000]] */
typedef uint64_t fiat_curve25519_loose_field_element[5];

/* The type fiat_curve25519_tight_field_element is a field element with tight bounds. */
/* Bounds: [[0x0 ~> 0x8000000000000], [0x0 ~> 0x8000000000000], [0x0 ~> 0x8000000000000], [0x0 ~> 0x8000000000000], [0x0 ~> 0x8000000000000]] */
typedef uint64_t fiat_curve25519_tight_field_element[5];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_curve25519_carry_square squares a field element and reduces the result.
 *
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * eval arg1) mod m
 *
 */
void fiat_curve25519_carry_square(fiat_curve25519_tight_field_element out1, const fiat_curve25519_loose_field_element arg1) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  fiat_curve25519_uint128 x9;
  fiat_curve25519_uint128 x10;
  fiat_curve25519_uint128 x11;
  fiat_curve25519_uint128 x12;
  fiat_curve25519_uint128 x13;
  fiat_curve25519_uint128 x14;
  fiat_curve25519_uint128 x15;
  fiat_curve25519_uint128 x16;
  fiat_curve25519_uint128 x17;
  fiat_curve25519_uint128 x18;
  fiat_curve25519_uint128 x19;
  fiat_curve25519_uint128 x20;
  fiat_curve25519_uint128 x21;
  fiat_curve25519_uint128 x22;
  fiat_curve25519_uint128 x23;
  fiat_curve25519_uint128 x24;
  uint64_t x25;
  uint64_t x26;
  fiat_curve25519_uint128 x27;
  fiat_curve25519_uint128 x28;
  fiat_curve25519_uint128 x29;
  fiat_curve25519_uint128 x30;
  fiat_curve25519_uint128 x31;
  uint64_t x32;
  uint64_t x33;
  fiat_curve25519_uint128 x34;
  uint64_t x35;
  uint64_t x36;
  fiat_curve25519_uint128 x37;
  uint64_t x38;
  uint64_t x39;
  fiat_curve25519_uint128 x40;
  uint64_t x41;
  uint64_t x42;
  uint64_t x43;
  uint64_t x44;
  uint64_t x45;
  uint64_t x46;
  uint64_t x47;
  fiat_curve25519_uint1 x48;
  uint64_t x49;
  uint64_t x50;
  x1 = ((arg1[4]) * UINT8_C(0x13));
  x2 = (x1 * 0x2);
  x3 = ((arg1[4]) * 0x2);
  x4 = ((arg1[3]) * UINT8_C(0x13));
  x5 = (x4 * 0x2);
  x6 = ((arg1[3]) * 0x2);
  x7 = ((arg1[2]) * 0x2);
  x8 = ((arg1[1]) * 0x2);
  x9 = ((fiat_curve25519_uint128)(arg1[4]) * x1);
  x10 = ((fiat_curve25519_uint128)(arg1[3]) * x2);
  x11 = ((fiat_curve25519_uint128)(arg1[3]) * x4);
  x12 = ((fiat_curve25519_uint128)(arg1[2]) * x2);
  x13 = ((fiat_curve25519_uint128)(arg1[2]) * x5);
  x14 = ((fiat_curve25519_uint128)(arg1[2]) * (arg1[2]));
  x15 = ((fiat_curve25519_uint128)(arg1[1]) * x2);
  x16 = ((fiat_curve25519_uint128)(arg1[1]) * x6);
  x17 = ((fiat_curve25519_uint128)(arg1[1]) * x7);
  x18 = ((fiat_curve25519_uint128)(arg1[1]) * (arg1[1]));
  x19 = ((fiat_curve25519_uint128)(arg1[0]) * x3);
  x20 = ((fiat_curve25519_uint128)(arg1[0]) * x6);
  x21 = ((fiat_curve25519_uint128)(arg1[0]) * x7);
  x22 = ((fiat_curve25519_uint128)(arg1[0]) * x8);
  x23 = ((fiat_curve25519_uint128)(arg1[0]) * (arg1[0]));
  x24 = (x23 + (x15 + x13));
  x25 = (uint64_t)(x24 >> 51);
  x26 = (uint64_t)(x24 & UINT64_C(0x7ffffffffffff));
  x27 = (x19 + (x16 + x14));
  x28 = (x20 + (x17 + x9));
  x29 = (x21 + (x18 + x10));
  x30 = (x22 + (x12 + x11));
  x31 = (x25 + x30);
  x32 = (uint64_t)(x31 >> 51);
  x33 = (uint64_t)(x31 & UINT64_C(0x7ffffffffffff));
  x34 = (x32 + x29);
  x35 = (uint64_t)(x34 >> 51);
  x36 = (uint64_t)(x34 & UINT64_C(0x7ffffffffffff));
  x37 = (x35 + x28);
  x38 = (uint64_t)(x37 >> 51);
  x39 = (uint64_t)(x37 & UINT64_C(0x7ffffffffffff));
  x40 = (x38 + x27);
  x41 = (uint64_t)(x40 >> 51);
  x42 = (uint64_t)(x40 & UINT64_C(0x7ffffffffffff));
  x43 = (x41 * UINT8_C(0x13));
  x44 = (x26 + x43);
  x45 = (x44 >> 51);
  x46 = (x44 & UINT64_C(0x7ffffffffffff));
  x47 = (x45 + x33);
  x48 = (fiat_curve25519_uint1)(x47 >> 51);
  x49 = (x47 & UINT64_C(0x7ffffffffffff));
  x50 = (x48 + x36);
  out1[0] = x46;
  out1[1] = x49;
  out1[2] = x50;
  out1[3] = x39;
  out1[4] = x42;
}
