/* Autogenerated: '/home/sabrina/CryptOpt/dist/data/fiat-bridge/unsaturated_solinas' --lang C --inline-internal --internal-static --use-value-barrier p448_solinas 64 8 '2^448 - 2^224 - 1' carry_mul */
/* curve description: p448_solinas */
/* machine_wordsize = 64 (from "64") */
/* requested operations: carry_mul */
/* n = 8 (from "8") */
/* s-c = 2^448 - [(2^224, 1), (1, 1)] (from "2^448 - 2^224 - 1") */
/* tight_bounds_multiplier = 1 (from "") */
/*  */
/* Computed values: */
/*   carry_chain = [3, 7, 4, 0, 5, 1, 6, 2, 7, 3, 4, 0] */
/*   eval z = z[0] + (z[1] << 56) + (z[2] << 112) + (z[3] << 168) + (z[4] << 224) + (z[5] << 0x118) + (z[6] << 0x150) + (z[7] << 0x188) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) + (z[32] << 256) + (z[33] << 0x108) + (z[34] << 0x110) + (z[35] << 0x118) + (z[36] << 0x120) + (z[37] << 0x128) + (z[38] << 0x130) + (z[39] << 0x138) + (z[40] << 0x140) + (z[41] << 0x148) + (z[42] << 0x150) + (z[43] << 0x158) + (z[44] << 0x160) + (z[45] << 0x168) + (z[46] << 0x170) + (z[47] << 0x178) + (z[48] << 0x180) + (z[49] << 0x188) + (z[50] << 0x190) + (z[51] << 0x198) + (z[52] << 0x1a0) + (z[53] << 0x1a8) + (z[54] << 0x1b0) + (z[55] << 0x1b8) */
/*   balance = [0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffc, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe] */

#include <stdint.h>
typedef unsigned char fiat_p448_solinas_uint1;
typedef signed char fiat_p448_solinas_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_P448_SOLINAS_FIAT_EXTENSION __extension__
#  define FIAT_P448_SOLINAS_FIAT_INLINE __inline__
#else
#  define FIAT_P448_SOLINAS_FIAT_EXTENSION
#  define FIAT_P448_SOLINAS_FIAT_INLINE
#endif

FIAT_P448_SOLINAS_FIAT_EXTENSION typedef signed __int128 fiat_p448_solinas_int128;
FIAT_P448_SOLINAS_FIAT_EXTENSION typedef unsigned __int128 fiat_p448_solinas_uint128;

/* The type fiat_p448_solinas_loose_field_element is a field element with loose bounds. */
/* Bounds: [[0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000]] */
typedef uint64_t fiat_p448_solinas_loose_field_element[8];

/* The type fiat_p448_solinas_tight_field_element is a field element with tight bounds. */
/* Bounds: [[0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000]] */
typedef uint64_t fiat_p448_solinas_tight_field_element[8];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_p448_solinas_carry_mul multiplies two field elements and reduces the result.
 *
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * eval arg2) mod m
 *
 */
void fiat_p448_solinas_carry_mul(fiat_p448_solinas_tight_field_element out1, const fiat_p448_solinas_loose_field_element arg1, const fiat_p448_solinas_loose_field_element arg2) {
  fiat_p448_solinas_uint128 x1;
  fiat_p448_solinas_uint128 x2;
  fiat_p448_solinas_uint128 x3;
  fiat_p448_solinas_uint128 x4;
  fiat_p448_solinas_uint128 x5;
  fiat_p448_solinas_uint128 x6;
  fiat_p448_solinas_uint128 x7;
  fiat_p448_solinas_uint128 x8;
  fiat_p448_solinas_uint128 x9;
  fiat_p448_solinas_uint128 x10;
  fiat_p448_solinas_uint128 x11;
  fiat_p448_solinas_uint128 x12;
  fiat_p448_solinas_uint128 x13;
  fiat_p448_solinas_uint128 x14;
  fiat_p448_solinas_uint128 x15;
  fiat_p448_solinas_uint128 x16;
  fiat_p448_solinas_uint128 x17;
  fiat_p448_solinas_uint128 x18;
  fiat_p448_solinas_uint128 x19;
  fiat_p448_solinas_uint128 x20;
  fiat_p448_solinas_uint128 x21;
  fiat_p448_solinas_uint128 x22;
  fiat_p448_solinas_uint128 x23;
  fiat_p448_solinas_uint128 x24;
  fiat_p448_solinas_uint128 x25;
  fiat_p448_solinas_uint128 x26;
  fiat_p448_solinas_uint128 x27;
  fiat_p448_solinas_uint128 x28;
  fiat_p448_solinas_uint128 x29;
  fiat_p448_solinas_uint128 x30;
  fiat_p448_solinas_uint128 x31;
  fiat_p448_solinas_uint128 x32;
  fiat_p448_solinas_uint128 x33;
  fiat_p448_solinas_uint128 x34;
  fiat_p448_solinas_uint128 x35;
  fiat_p448_solinas_uint128 x36;
  fiat_p448_solinas_uint128 x37;
  fiat_p448_solinas_uint128 x38;
  fiat_p448_solinas_uint128 x39;
  fiat_p448_solinas_uint128 x40;
  fiat_p448_solinas_uint128 x41;
  fiat_p448_solinas_uint128 x42;
  fiat_p448_solinas_uint128 x43;
  fiat_p448_solinas_uint128 x44;
  fiat_p448_solinas_uint128 x45;
  fiat_p448_solinas_uint128 x46;
  fiat_p448_solinas_uint128 x47;
  fiat_p448_solinas_uint128 x48;
  fiat_p448_solinas_uint128 x49;
  fiat_p448_solinas_uint128 x50;
  fiat_p448_solinas_uint128 x51;
  fiat_p448_solinas_uint128 x52;
  fiat_p448_solinas_uint128 x53;
  fiat_p448_solinas_uint128 x54;
  fiat_p448_solinas_uint128 x55;
  fiat_p448_solinas_uint128 x56;
  fiat_p448_solinas_uint128 x57;
  fiat_p448_solinas_uint128 x58;
  fiat_p448_solinas_uint128 x59;
  fiat_p448_solinas_uint128 x60;
  fiat_p448_solinas_uint128 x61;
  fiat_p448_solinas_uint128 x62;
  fiat_p448_solinas_uint128 x63;
  fiat_p448_solinas_uint128 x64;
  fiat_p448_solinas_uint128 x65;
  fiat_p448_solinas_uint128 x66;
  fiat_p448_solinas_uint128 x67;
  fiat_p448_solinas_uint128 x68;
  fiat_p448_solinas_uint128 x69;
  fiat_p448_solinas_uint128 x70;
  fiat_p448_solinas_uint128 x71;
  fiat_p448_solinas_uint128 x72;
  fiat_p448_solinas_uint128 x73;
  fiat_p448_solinas_uint128 x74;
  fiat_p448_solinas_uint128 x75;
  fiat_p448_solinas_uint128 x76;
  fiat_p448_solinas_uint128 x77;
  fiat_p448_solinas_uint128 x78;
  fiat_p448_solinas_uint128 x79;
  fiat_p448_solinas_uint128 x80;
  fiat_p448_solinas_uint128 x81;
  fiat_p448_solinas_uint128 x82;
  fiat_p448_solinas_uint128 x83;
  fiat_p448_solinas_uint128 x84;
  fiat_p448_solinas_uint128 x85;
  fiat_p448_solinas_uint128 x86;
  fiat_p448_solinas_uint128 x87;
  fiat_p448_solinas_uint128 x88;
  fiat_p448_solinas_uint128 x89;
  fiat_p448_solinas_uint128 x90;
  fiat_p448_solinas_uint128 x91;
  fiat_p448_solinas_uint128 x92;
  fiat_p448_solinas_uint128 x93;
  fiat_p448_solinas_uint128 x94;
  fiat_p448_solinas_uint128 x95;
  fiat_p448_solinas_uint128 x96;
  fiat_p448_solinas_uint128 x97;
  fiat_p448_solinas_uint128 x98;
  fiat_p448_solinas_uint128 x99;
  uint64_t x100;
  uint64_t x101;
  fiat_p448_solinas_uint128 x102;
  fiat_p448_solinas_uint128 x103;
  fiat_p448_solinas_uint128 x104;
  fiat_p448_solinas_uint128 x105;
  fiat_p448_solinas_uint128 x106;
  fiat_p448_solinas_uint128 x107;
  fiat_p448_solinas_uint128 x108;
  fiat_p448_solinas_uint128 x109;
  uint64_t x110;
  uint64_t x111;
  fiat_p448_solinas_uint128 x112;
  uint64_t x113;
  uint64_t x114;
  fiat_p448_solinas_uint128 x115;
  fiat_p448_solinas_uint128 x116;
  uint64_t x117;
  uint64_t x118;
  fiat_p448_solinas_uint128 x119;
  uint64_t x120;
  uint64_t x121;
  fiat_p448_solinas_uint128 x122;
  uint64_t x123;
  uint64_t x124;
  fiat_p448_solinas_uint128 x125;
  uint64_t x126;
  uint64_t x127;
  uint64_t x128;
  uint64_t x129;
  uint64_t x130;
  uint64_t x131;
  uint64_t x132;
  uint64_t x133;
  uint64_t x134;
  uint64_t x135;
  uint64_t x136;
  uint64_t x137;
  uint64_t x138;
  fiat_p448_solinas_uint1 x139;
  uint64_t x140;
  uint64_t x141;
  fiat_p448_solinas_uint1 x142;
  uint64_t x143;
  uint64_t x144;
  x1 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[7]));
  x2 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[6]));
  x3 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[5]));
  x4 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[7]));
  x5 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[6]));
  x6 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[7]));
  x7 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[7]));
  x8 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[6]));
  x9 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[5]));
  x10 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[7]));
  x11 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[6]));
  x12 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[7]));
  x13 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[7]));
  x14 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[6]));
  x15 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[5]));
  x16 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[4]));
  x17 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[3]));
  x18 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[2]));
  x19 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[1]));
  x20 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[7]));
  x21 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[6]));
  x22 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[5]));
  x23 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[4]));
  x24 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[3]));
  x25 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[2]));
  x26 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[7]));
  x27 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[6]));
  x28 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[5]));
  x29 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[4]));
  x30 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[3]));
  x31 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[7]));
  x32 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[6]));
  x33 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[5]));
  x34 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[4]));
  x35 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg2[7]));
  x36 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg2[6]));
  x37 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg2[5]));
  x38 = ((fiat_p448_solinas_uint128)(arg1[2]) * (arg2[7]));
  x39 = ((fiat_p448_solinas_uint128)(arg1[2]) * (arg2[6]));
  x40 = ((fiat_p448_solinas_uint128)(arg1[1]) * (arg2[7]));
  x41 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[4]));
  x42 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[3]));
  x43 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[2]));
  x44 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[1]));
  x45 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[5]));
  x46 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[4]));
  x47 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[3]));
  x48 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[2]));
  x49 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[6]));
  x50 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[5]));
  x51 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[4]));
  x52 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[3]));
  x53 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[7]));
  x54 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[6]));
  x55 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[5]));
  x56 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[4]));
  x57 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg2[7]));
  x58 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg2[6]));
  x59 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg2[5]));
  x60 = ((fiat_p448_solinas_uint128)(arg1[2]) * (arg2[7]));
  x61 = ((fiat_p448_solinas_uint128)(arg1[2]) * (arg2[6]));
  x62 = ((fiat_p448_solinas_uint128)(arg1[1]) * (arg2[7]));
  x63 = ((fiat_p448_solinas_uint128)(arg1[7]) * (arg2[0]));
  x64 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[1]));
  x65 = ((fiat_p448_solinas_uint128)(arg1[6]) * (arg2[0]));
  x66 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[2]));
  x67 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[1]));
  x68 = ((fiat_p448_solinas_uint128)(arg1[5]) * (arg2[0]));
  x69 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[3]));
  x70 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[2]));
  x71 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[1]));
  x72 = ((fiat_p448_solinas_uint128)(arg1[4]) * (arg2[0]));
  x73 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg2[4]));
  x74 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg2[3]));
  x75 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg2[2]));
  x76 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg2[1]));
  x77 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg2[0]));
  x78 = ((fiat_p448_solinas_uint128)(arg1[2]) * (arg2[5]));
  x79 = ((fiat_p448_solinas_uint128)(arg1[2]) * (arg2[4]));
  x80 = ((fiat_p448_solinas_uint128)(arg1[2]) * (arg2[3]));
  x81 = ((fiat_p448_solinas_uint128)(arg1[2]) * (arg2[2]));
  x82 = ((fiat_p448_solinas_uint128)(arg1[2]) * (arg2[1]));
  x83 = ((fiat_p448_solinas_uint128)(arg1[2]) * (arg2[0]));
  x84 = ((fiat_p448_solinas_uint128)(arg1[1]) * (arg2[6]));
  x85 = ((fiat_p448_solinas_uint128)(arg1[1]) * (arg2[5]));
  x86 = ((fiat_p448_solinas_uint128)(arg1[1]) * (arg2[4]));
  x87 = ((fiat_p448_solinas_uint128)(arg1[1]) * (arg2[3]));
  x88 = ((fiat_p448_solinas_uint128)(arg1[1]) * (arg2[2]));
  x89 = ((fiat_p448_solinas_uint128)(arg1[1]) * (arg2[1]));
  x90 = ((fiat_p448_solinas_uint128)(arg1[1]) * (arg2[0]));
  x91 = ((fiat_p448_solinas_uint128)(arg1[0]) * (arg2[7]));
  x92 = ((fiat_p448_solinas_uint128)(arg1[0]) * (arg2[6]));
  x93 = ((fiat_p448_solinas_uint128)(arg1[0]) * (arg2[5]));
  x94 = ((fiat_p448_solinas_uint128)(arg1[0]) * (arg2[4]));
  x95 = ((fiat_p448_solinas_uint128)(arg1[0]) * (arg2[3]));
  x96 = ((fiat_p448_solinas_uint128)(arg1[0]) * (arg2[2]));
  x97 = ((fiat_p448_solinas_uint128)(arg1[0]) * (arg2[1]));
  x98 = ((fiat_p448_solinas_uint128)(arg1[0]) * (arg2[0]));
  x99 = (x95 + (x88 + (x82 + (x77 + (x31 + (x27 + (x22 + x16)))))));
  x100 = (uint64_t)(x99 >> 56);
  x101 = (uint64_t)(x99 & UINT64_C(0xffffffffffffff));
  x102 = (x91 + (x84 + (x78 + (x73 + (x69 + (x66 + (x64 + (x63 + (x53 + (x49 + (x45 + x41)))))))))));
  x103 = (x92 + (x85 + (x79 + (x74 + (x70 + (x67 + (x65 + (x57 + (x54 + (x50 + (x46 + (x42 + (x13 + x7)))))))))))));
  x104 = (x93 + (x86 + (x80 + (x75 + (x71 + (x68 + (x60 + (x58 + (x55 + (x51 + (x47 + (x43 + (x20 + (x14 + (x10 + x8)))))))))))))));
  x105 = (x94 + (x87 + (x81 + (x76 + (x72 + (x62 + (x61 + (x59 + (x56 + (x52 + (x48 + (x44 + (x26 + (x21 + (x15 + (x12 + (x11 + x9)))))))))))))))));
  x106 = (x96 + (x89 + (x83 + (x35 + (x32 + (x28 + (x23 + (x17 + x1))))))));
  x107 = (x97 + (x90 + (x38 + (x36 + (x33 + (x29 + (x24 + (x18 + (x4 + x2)))))))));
  x108 = (x98 + (x40 + (x39 + (x37 + (x34 + (x30 + (x25 + (x19 + (x6 + (x5 + x3))))))))));
  x109 = (x100 + x105);
  x110 = (uint64_t)(x102 >> 56);
  x111 = (uint64_t)(x102 & UINT64_C(0xffffffffffffff));
  x112 = (x109 + x110);
  x113 = (uint64_t)(x112 >> 56);
  x114 = (uint64_t)(x112 & UINT64_C(0xffffffffffffff));
  x115 = (x108 + x110);
  x116 = (x113 + x104);
  x117 = (uint64_t)(x115 >> 56);
  x118 = (uint64_t)(x115 & UINT64_C(0xffffffffffffff));
  x119 = (x117 + x107);
  x120 = (uint64_t)(x116 >> 56);
  x121 = (uint64_t)(x116 & UINT64_C(0xffffffffffffff));
  x122 = (x120 + x103);
  x123 = (uint64_t)(x119 >> 56);
  x124 = (uint64_t)(x119 & UINT64_C(0xffffffffffffff));
  x125 = (x123 + x106);
  x126 = (uint64_t)(x122 >> 56);
  x127 = (uint64_t)(x122 & UINT64_C(0xffffffffffffff));
  x128 = (x126 + x111);
  x129 = (uint64_t)(x125 >> 56);
  x130 = (uint64_t)(x125 & UINT64_C(0xffffffffffffff));
  x131 = (x129 + x101);
  x132 = (x128 >> 56);
  x133 = (x128 & UINT64_C(0xffffffffffffff));
  x134 = (x131 >> 56);
  x135 = (x131 & UINT64_C(0xffffffffffffff));
  x136 = (x114 + x132);
  x137 = (x118 + x132);
  x138 = (x134 + x136);
  x139 = (fiat_p448_solinas_uint1)(x138 >> 56);
  x140 = (x138 & UINT64_C(0xffffffffffffff));
  x141 = (x139 + x121);
  x142 = (fiat_p448_solinas_uint1)(x137 >> 56);
  x143 = (x137 & UINT64_C(0xffffffffffffff));
  x144 = (x142 + x124);
  out1[0] = x143;
  out1[1] = x144;
  out1[2] = x130;
  out1[3] = x135;
  out1[4] = x140;
  out1[5] = x141;
  out1[6] = x127;
  out1[7] = x133;
}
