/* Autogenerated: '/home/sabrina/CryptOpt/dist/data/fiat-bridge/unsaturated_solinas' --lang C --inline-internal --internal-static --use-value-barrier p448_solinas 64 8 '2^448 - 2^224 - 1' carry_square */
/* curve description: p448_solinas */
/* machine_wordsize = 64 (from "64") */
/* requested operations: carry_square */
/* n = 8 (from "8") */
/* s-c = 2^448 - [(2^224, 1), (1, 1)] (from "2^448 - 2^224 - 1") */
/* tight_bounds_multiplier = 1 (from "") */
/*  */
/* Computed values: */
/*   carry_chain = [3, 7, 4, 0, 5, 1, 6, 2, 7, 3, 4, 0] */
/*   eval z = z[0] + (z[1] << 56) + (z[2] << 112) + (z[3] << 168) + (z[4] << 224) + (z[5] << 0x118) + (z[6] << 0x150) + (z[7] << 0x188) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) + (z[32] << 256) + (z[33] << 0x108) + (z[34] << 0x110) + (z[35] << 0x118) + (z[36] << 0x120) + (z[37] << 0x128) + (z[38] << 0x130) + (z[39] << 0x138) + (z[40] << 0x140) + (z[41] << 0x148) + (z[42] << 0x150) + (z[43] << 0x158) + (z[44] << 0x160) + (z[45] << 0x168) + (z[46] << 0x170) + (z[47] << 0x178) + (z[48] << 0x180) + (z[49] << 0x188) + (z[50] << 0x190) + (z[51] << 0x198) + (z[52] << 0x1a0) + (z[53] << 0x1a8) + (z[54] << 0x1b0) + (z[55] << 0x1b8) */
/*   balance = [0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffc, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe] */

#include <stdint.h>
typedef unsigned char fiat_p448_solinas_uint1;
typedef signed char fiat_p448_solinas_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_P448_SOLINAS_FIAT_EXTENSION __extension__
#  define FIAT_P448_SOLINAS_FIAT_INLINE __inline__
#else
#  define FIAT_P448_SOLINAS_FIAT_EXTENSION
#  define FIAT_P448_SOLINAS_FIAT_INLINE
#endif

FIAT_P448_SOLINAS_FIAT_EXTENSION typedef signed __int128 fiat_p448_solinas_int128;
FIAT_P448_SOLINAS_FIAT_EXTENSION typedef unsigned __int128 fiat_p448_solinas_uint128;

/* The type fiat_p448_solinas_loose_field_element is a field element with loose bounds. */
/* Bounds: [[0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000]] */
typedef uint64_t fiat_p448_solinas_loose_field_element[8];

/* The type fiat_p448_solinas_tight_field_element is a field element with tight bounds. */
/* Bounds: [[0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000]] */
typedef uint64_t fiat_p448_solinas_tight_field_element[8];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_p448_solinas_carry_square squares a field element and reduces the result.
 *
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * eval arg1) mod m
 *
 */
void fiat_p448_solinas_carry_square(fiat_p448_solinas_tight_field_element out1, const fiat_p448_solinas_loose_field_element arg1) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  uint64_t x17;
  uint64_t x18;
  uint64_t x19;
  uint64_t x20;
  uint64_t x21;
  fiat_p448_solinas_uint128 x22;
  fiat_p448_solinas_uint128 x23;
  fiat_p448_solinas_uint128 x24;
  fiat_p448_solinas_uint128 x25;
  fiat_p448_solinas_uint128 x26;
  fiat_p448_solinas_uint128 x27;
  fiat_p448_solinas_uint128 x28;
  fiat_p448_solinas_uint128 x29;
  fiat_p448_solinas_uint128 x30;
  fiat_p448_solinas_uint128 x31;
  fiat_p448_solinas_uint128 x32;
  fiat_p448_solinas_uint128 x33;
  fiat_p448_solinas_uint128 x34;
  fiat_p448_solinas_uint128 x35;
  fiat_p448_solinas_uint128 x36;
  fiat_p448_solinas_uint128 x37;
  fiat_p448_solinas_uint128 x38;
  fiat_p448_solinas_uint128 x39;
  fiat_p448_solinas_uint128 x40;
  fiat_p448_solinas_uint128 x41;
  fiat_p448_solinas_uint128 x42;
  fiat_p448_solinas_uint128 x43;
  fiat_p448_solinas_uint128 x44;
  fiat_p448_solinas_uint128 x45;
  fiat_p448_solinas_uint128 x46;
  fiat_p448_solinas_uint128 x47;
  fiat_p448_solinas_uint128 x48;
  fiat_p448_solinas_uint128 x49;
  fiat_p448_solinas_uint128 x50;
  fiat_p448_solinas_uint128 x51;
  fiat_p448_solinas_uint128 x52;
  fiat_p448_solinas_uint128 x53;
  fiat_p448_solinas_uint128 x54;
  fiat_p448_solinas_uint128 x55;
  fiat_p448_solinas_uint128 x56;
  fiat_p448_solinas_uint128 x57;
  fiat_p448_solinas_uint128 x58;
  fiat_p448_solinas_uint128 x59;
  fiat_p448_solinas_uint128 x60;
  fiat_p448_solinas_uint128 x61;
  fiat_p448_solinas_uint128 x62;
  fiat_p448_solinas_uint128 x63;
  fiat_p448_solinas_uint128 x64;
  fiat_p448_solinas_uint128 x65;
  fiat_p448_solinas_uint128 x66;
  fiat_p448_solinas_uint128 x67;
  fiat_p448_solinas_uint128 x68;
  fiat_p448_solinas_uint128 x69;
  fiat_p448_solinas_uint128 x70;
  fiat_p448_solinas_uint128 x71;
  fiat_p448_solinas_uint128 x72;
  fiat_p448_solinas_uint128 x73;
  fiat_p448_solinas_uint128 x74;
  fiat_p448_solinas_uint128 x75;
  fiat_p448_solinas_uint128 x76;
  fiat_p448_solinas_uint128 x77;
  fiat_p448_solinas_uint128 x78;
  uint64_t x79;
  uint64_t x80;
  fiat_p448_solinas_uint128 x81;
  fiat_p448_solinas_uint128 x82;
  fiat_p448_solinas_uint128 x83;
  fiat_p448_solinas_uint128 x84;
  fiat_p448_solinas_uint128 x85;
  fiat_p448_solinas_uint128 x86;
  fiat_p448_solinas_uint128 x87;
  fiat_p448_solinas_uint128 x88;
  uint64_t x89;
  uint64_t x90;
  fiat_p448_solinas_uint128 x91;
  uint64_t x92;
  uint64_t x93;
  fiat_p448_solinas_uint128 x94;
  fiat_p448_solinas_uint128 x95;
  uint64_t x96;
  uint64_t x97;
  fiat_p448_solinas_uint128 x98;
  uint64_t x99;
  uint64_t x100;
  fiat_p448_solinas_uint128 x101;
  uint64_t x102;
  uint64_t x103;
  fiat_p448_solinas_uint128 x104;
  uint64_t x105;
  uint64_t x106;
  uint64_t x107;
  uint64_t x108;
  uint64_t x109;
  uint64_t x110;
  uint64_t x111;
  uint64_t x112;
  uint64_t x113;
  uint64_t x114;
  uint64_t x115;
  uint64_t x116;
  uint64_t x117;
  fiat_p448_solinas_uint1 x118;
  uint64_t x119;
  uint64_t x120;
  fiat_p448_solinas_uint1 x121;
  uint64_t x122;
  uint64_t x123;
  x1 = (arg1[7]);
  x2 = (arg1[7]);
  x3 = (x1 * 0x2);
  x4 = (x2 * 0x2);
  x5 = ((arg1[7]) * 0x2);
  x6 = (arg1[6]);
  x7 = (arg1[6]);
  x8 = (x6 * 0x2);
  x9 = (x7 * 0x2);
  x10 = ((arg1[6]) * 0x2);
  x11 = (arg1[5]);
  x12 = (arg1[5]);
  x13 = (x11 * 0x2);
  x14 = (x12 * 0x2);
  x15 = ((arg1[5]) * 0x2);
  x16 = (arg1[4]);
  x17 = (arg1[4]);
  x18 = ((arg1[4]) * 0x2);
  x19 = ((arg1[3]) * 0x2);
  x20 = ((arg1[2]) * 0x2);
  x21 = ((arg1[1]) * 0x2);
  x22 = ((fiat_p448_solinas_uint128)(arg1[7]) * x1);
  x23 = ((fiat_p448_solinas_uint128)(arg1[6]) * x3);
  x24 = ((fiat_p448_solinas_uint128)(arg1[6]) * x6);
  x25 = ((fiat_p448_solinas_uint128)(arg1[5]) * x3);
  x26 = ((fiat_p448_solinas_uint128)(arg1[7]) * x1);
  x27 = ((fiat_p448_solinas_uint128)(arg1[6]) * x3);
  x28 = ((fiat_p448_solinas_uint128)(arg1[6]) * x6);
  x29 = ((fiat_p448_solinas_uint128)(arg1[5]) * x3);
  x30 = ((fiat_p448_solinas_uint128)(arg1[7]) * x2);
  x31 = ((fiat_p448_solinas_uint128)(arg1[6]) * x4);
  x32 = ((fiat_p448_solinas_uint128)(arg1[6]) * x7);
  x33 = ((fiat_p448_solinas_uint128)(arg1[5]) * x4);
  x34 = ((fiat_p448_solinas_uint128)(arg1[5]) * x9);
  x35 = ((fiat_p448_solinas_uint128)(arg1[5]) * x8);
  x36 = ((fiat_p448_solinas_uint128)(arg1[5]) * x12);
  x37 = ((fiat_p448_solinas_uint128)(arg1[5]) * x11);
  x38 = ((fiat_p448_solinas_uint128)(arg1[4]) * x4);
  x39 = ((fiat_p448_solinas_uint128)(arg1[4]) * x3);
  x40 = ((fiat_p448_solinas_uint128)(arg1[4]) * x9);
  x41 = ((fiat_p448_solinas_uint128)(arg1[4]) * x8);
  x42 = ((fiat_p448_solinas_uint128)(arg1[4]) * x14);
  x43 = ((fiat_p448_solinas_uint128)(arg1[4]) * x13);
  x44 = ((fiat_p448_solinas_uint128)(arg1[4]) * x17);
  x45 = ((fiat_p448_solinas_uint128)(arg1[4]) * x16);
  x46 = ((fiat_p448_solinas_uint128)(arg1[3]) * x4);
  x47 = ((fiat_p448_solinas_uint128)(arg1[3]) * x3);
  x48 = ((fiat_p448_solinas_uint128)(arg1[3]) * x9);
  x49 = ((fiat_p448_solinas_uint128)(arg1[3]) * x8);
  x50 = ((fiat_p448_solinas_uint128)(arg1[3]) * x14);
  x51 = ((fiat_p448_solinas_uint128)(arg1[3]) * x13);
  x52 = ((fiat_p448_solinas_uint128)(arg1[3]) * x18);
  x53 = ((fiat_p448_solinas_uint128)(arg1[3]) * (arg1[3]));
  x54 = ((fiat_p448_solinas_uint128)(arg1[2]) * x4);
  x55 = ((fiat_p448_solinas_uint128)(arg1[2]) * x3);
  x56 = ((fiat_p448_solinas_uint128)(arg1[2]) * x9);
  x57 = ((fiat_p448_solinas_uint128)(arg1[2]) * x8);
  x58 = ((fiat_p448_solinas_uint128)(arg1[2]) * x15);
  x59 = ((fiat_p448_solinas_uint128)(arg1[2]) * x18);
  x60 = ((fiat_p448_solinas_uint128)(arg1[2]) * x19);
  x61 = ((fiat_p448_solinas_uint128)(arg1[2]) * (arg1[2]));
  x62 = ((fiat_p448_solinas_uint128)(arg1[1]) * x4);
  x63 = ((fiat_p448_solinas_uint128)(arg1[1]) * x3);
  x64 = ((fiat_p448_solinas_uint128)(arg1[1]) * x10);
  x65 = ((fiat_p448_solinas_uint128)(arg1[1]) * x15);
  x66 = ((fiat_p448_solinas_uint128)(arg1[1]) * x18);
  x67 = ((fiat_p448_solinas_uint128)(arg1[1]) * x19);
  x68 = ((fiat_p448_solinas_uint128)(arg1[1]) * x20);
  x69 = ((fiat_p448_solinas_uint128)(arg1[1]) * (arg1[1]));
  x70 = ((fiat_p448_solinas_uint128)(arg1[0]) * x5);
  x71 = ((fiat_p448_solinas_uint128)(arg1[0]) * x10);
  x72 = ((fiat_p448_solinas_uint128)(arg1[0]) * x15);
  x73 = ((fiat_p448_solinas_uint128)(arg1[0]) * x18);
  x74 = ((fiat_p448_solinas_uint128)(arg1[0]) * x19);
  x75 = ((fiat_p448_solinas_uint128)(arg1[0]) * x20);
  x76 = ((fiat_p448_solinas_uint128)(arg1[0]) * x21);
  x77 = ((fiat_p448_solinas_uint128)(arg1[0]) * (arg1[0]));
  x78 = (x74 + (x68 + (x38 + x34)));
  x79 = (uint64_t)(x78 >> 56);
  x80 = (uint64_t)(x78 & UINT64_C(0xffffffffffffff));
  x81 = (x70 + (x64 + (x58 + (x52 + (x39 + x35)))));
  x82 = (x71 + (x65 + (x59 + (x53 + (x47 + (x41 + (x37 + (x30 + x26))))))));
  x83 = (x72 + (x66 + (x60 + (x55 + (x49 + (x43 + (x31 + x27)))))));
  x84 = (x73 + (x67 + (x63 + (x61 + (x57 + (x51 + (x45 + (x33 + (x32 + (x29 + x28))))))))));
  x85 = (x75 + (x69 + (x46 + (x40 + (x36 + x22)))));
  x86 = (x76 + (x54 + (x48 + (x42 + x23))));
  x87 = (x77 + (x62 + (x56 + (x50 + (x44 + (x25 + x24))))));
  x88 = (x79 + x84);
  x89 = (uint64_t)(x81 >> 56);
  x90 = (uint64_t)(x81 & UINT64_C(0xffffffffffffff));
  x91 = (x88 + x89);
  x92 = (uint64_t)(x91 >> 56);
  x93 = (uint64_t)(x91 & UINT64_C(0xffffffffffffff));
  x94 = (x87 + x89);
  x95 = (x92 + x83);
  x96 = (uint64_t)(x94 >> 56);
  x97 = (uint64_t)(x94 & UINT64_C(0xffffffffffffff));
  x98 = (x96 + x86);
  x99 = (uint64_t)(x95 >> 56);
  x100 = (uint64_t)(x95 & UINT64_C(0xffffffffffffff));
  x101 = (x99 + x82);
  x102 = (uint64_t)(x98 >> 56);
  x103 = (uint64_t)(x98 & UINT64_C(0xffffffffffffff));
  x104 = (x102 + x85);
  x105 = (uint64_t)(x101 >> 56);
  x106 = (uint64_t)(x101 & UINT64_C(0xffffffffffffff));
  x107 = (x105 + x90);
  x108 = (uint64_t)(x104 >> 56);
  x109 = (uint64_t)(x104 & UINT64_C(0xffffffffffffff));
  x110 = (x108 + x80);
  x111 = (x107 >> 56);
  x112 = (x107 & UINT64_C(0xffffffffffffff));
  x113 = (x110 >> 56);
  x114 = (x110 & UINT64_C(0xffffffffffffff));
  x115 = (x93 + x111);
  x116 = (x97 + x111);
  x117 = (x113 + x115);
  x118 = (fiat_p448_solinas_uint1)(x117 >> 56);
  x119 = (x117 & UINT64_C(0xffffffffffffff));
  x120 = (x118 + x100);
  x121 = (fiat_p448_solinas_uint1)(x116 >> 56);
  x122 = (x116 & UINT64_C(0xffffffffffffff));
  x123 = (x121 + x103);
  out1[0] = x122;
  out1[1] = x123;
  out1[2] = x109;
  out1[3] = x114;
  out1[4] = x119;
  out1[5] = x120;
  out1[6] = x106;
  out1[7] = x112;
}
