/* Autogenerated: '/home/sabrina/CryptOpt/dist/data/fiat-bridge/unsaturated_solinas' --lang C --inline-internal --internal-static --use-value-barrier p521 64 9 '2^521 - 1' carry_mul */
/* curve description: p521 */
/* machine_wordsize = 64 (from "64") */
/* requested operations: carry_mul */
/* n = 9 (from "9") */
/* s-c = 2^521 - [(1, 1)] (from "2^521 - 1") */
/* tight_bounds_multiplier = 1 (from "") */
/*  */
/* Computed values: */
/*   carry_chain = [0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1] */
/*   eval z = z[0] + (z[1] << 58) + (z[2] << 116) + (z[3] << 174) + (z[4] << 232) + (z[5] << 0x122) + (z[6] << 0x15c) + (z[7] << 0x196) + (z[8] << 0x1d0) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) + (z[32] << 256) + (z[33] << 0x108) + (z[34] << 0x110) + (z[35] << 0x118) + (z[36] << 0x120) + (z[37] << 0x128) + (z[38] << 0x130) + (z[39] << 0x138) + (z[40] << 0x140) + (z[41] << 0x148) + (z[42] << 0x150) + (z[43] << 0x158) + (z[44] << 0x160) + (z[45] << 0x168) + (z[46] << 0x170) + (z[47] << 0x178) + (z[48] << 0x180) + (z[49] << 0x188) + (z[50] << 0x190) + (z[51] << 0x198) + (z[52] << 0x1a0) + (z[53] << 0x1a8) + (z[54] << 0x1b0) + (z[55] << 0x1b8) + (z[56] << 0x1c0) + (z[57] << 0x1c8) + (z[58] << 0x1d0) + (z[59] << 0x1d8) + (z[60] << 0x1e0) + (z[61] << 0x1e8) + (z[62] << 0x1f0) + (z[63] << 0x1f8) + (z[64] << 2^9) + (z[65] << 0x208) */
/*   balance = [0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x3fffffffffffffe] */

#include <stdint.h>
typedef unsigned char fiat_p521_uint1;
typedef signed char fiat_p521_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_P521_FIAT_EXTENSION __extension__
#  define FIAT_P521_FIAT_INLINE __inline__
#else
#  define FIAT_P521_FIAT_EXTENSION
#  define FIAT_P521_FIAT_INLINE
#endif

FIAT_P521_FIAT_EXTENSION typedef signed __int128 fiat_p521_int128;
FIAT_P521_FIAT_EXTENSION typedef unsigned __int128 fiat_p521_uint128;

/* The type fiat_p521_loose_field_element is a field element with loose bounds. */
/* Bounds: [[0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0x600000000000000]] */
typedef uint64_t fiat_p521_loose_field_element[9];

/* The type fiat_p521_tight_field_element is a field element with tight bounds. */
/* Bounds: [[0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x200000000000000]] */
typedef uint64_t fiat_p521_tight_field_element[9];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_p521_carry_mul multiplies two field elements and reduces the result.
 *
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * eval arg2) mod m
 *
 */
void fiat_p521_carry_mul(fiat_p521_tight_field_element out1, const fiat_p521_loose_field_element arg1, const fiat_p521_loose_field_element arg2) {
  fiat_p521_uint128 x1;
  fiat_p521_uint128 x2;
  fiat_p521_uint128 x3;
  fiat_p521_uint128 x4;
  fiat_p521_uint128 x5;
  fiat_p521_uint128 x6;
  fiat_p521_uint128 x7;
  fiat_p521_uint128 x8;
  fiat_p521_uint128 x9;
  fiat_p521_uint128 x10;
  fiat_p521_uint128 x11;
  fiat_p521_uint128 x12;
  fiat_p521_uint128 x13;
  fiat_p521_uint128 x14;
  fiat_p521_uint128 x15;
  fiat_p521_uint128 x16;
  fiat_p521_uint128 x17;
  fiat_p521_uint128 x18;
  fiat_p521_uint128 x19;
  fiat_p521_uint128 x20;
  fiat_p521_uint128 x21;
  fiat_p521_uint128 x22;
  fiat_p521_uint128 x23;
  fiat_p521_uint128 x24;
  fiat_p521_uint128 x25;
  fiat_p521_uint128 x26;
  fiat_p521_uint128 x27;
  fiat_p521_uint128 x28;
  fiat_p521_uint128 x29;
  fiat_p521_uint128 x30;
  fiat_p521_uint128 x31;
  fiat_p521_uint128 x32;
  fiat_p521_uint128 x33;
  fiat_p521_uint128 x34;
  fiat_p521_uint128 x35;
  fiat_p521_uint128 x36;
  fiat_p521_uint128 x37;
  fiat_p521_uint128 x38;
  fiat_p521_uint128 x39;
  fiat_p521_uint128 x40;
  fiat_p521_uint128 x41;
  fiat_p521_uint128 x42;
  fiat_p521_uint128 x43;
  fiat_p521_uint128 x44;
  fiat_p521_uint128 x45;
  fiat_p521_uint128 x46;
  fiat_p521_uint128 x47;
  fiat_p521_uint128 x48;
  fiat_p521_uint128 x49;
  fiat_p521_uint128 x50;
  fiat_p521_uint128 x51;
  fiat_p521_uint128 x52;
  fiat_p521_uint128 x53;
  fiat_p521_uint128 x54;
  fiat_p521_uint128 x55;
  fiat_p521_uint128 x56;
  fiat_p521_uint128 x57;
  fiat_p521_uint128 x58;
  fiat_p521_uint128 x59;
  fiat_p521_uint128 x60;
  fiat_p521_uint128 x61;
  fiat_p521_uint128 x62;
  fiat_p521_uint128 x63;
  fiat_p521_uint128 x64;
  fiat_p521_uint128 x65;
  fiat_p521_uint128 x66;
  fiat_p521_uint128 x67;
  fiat_p521_uint128 x68;
  fiat_p521_uint128 x69;
  fiat_p521_uint128 x70;
  fiat_p521_uint128 x71;
  fiat_p521_uint128 x72;
  fiat_p521_uint128 x73;
  fiat_p521_uint128 x74;
  fiat_p521_uint128 x75;
  fiat_p521_uint128 x76;
  fiat_p521_uint128 x77;
  fiat_p521_uint128 x78;
  fiat_p521_uint128 x79;
  fiat_p521_uint128 x80;
  fiat_p521_uint128 x81;
  fiat_p521_uint128 x82;
  fiat_p521_uint128 x83;
  uint64_t x84;
  fiat_p521_uint128 x85;
  fiat_p521_uint128 x86;
  fiat_p521_uint128 x87;
  fiat_p521_uint128 x88;
  fiat_p521_uint128 x89;
  fiat_p521_uint128 x90;
  fiat_p521_uint128 x91;
  fiat_p521_uint128 x92;
  fiat_p521_uint128 x93;
  fiat_p521_uint128 x94;
  uint64_t x95;
  fiat_p521_uint128 x96;
  fiat_p521_uint128 x97;
  uint64_t x98;
  fiat_p521_uint128 x99;
  fiat_p521_uint128 x100;
  uint64_t x101;
  fiat_p521_uint128 x102;
  fiat_p521_uint128 x103;
  uint64_t x104;
  fiat_p521_uint128 x105;
  fiat_p521_uint128 x106;
  uint64_t x107;
  fiat_p521_uint128 x108;
  fiat_p521_uint128 x109;
  uint64_t x110;
  fiat_p521_uint128 x111;
  fiat_p521_uint128 x112;
  uint64_t x113;
  fiat_p521_uint128 x114;
  fiat_p521_uint128 x115;
  uint64_t x116;
  fiat_p521_uint128 x117;
  uint64_t x118;
  uint64_t x119;
  uint64_t x120;
  fiat_p521_uint1 x121;
  uint64_t x122;
  uint64_t x123;
  x1 = ((fiat_p521_uint128)(arg1[8]) * ((arg2[8]) * 0x2));
  x2 = ((fiat_p521_uint128)(arg1[8]) * ((arg2[7]) * 0x2));
  x3 = ((fiat_p521_uint128)(arg1[8]) * ((arg2[6]) * 0x2));
  x4 = ((fiat_p521_uint128)(arg1[8]) * ((arg2[5]) * 0x2));
  x5 = ((fiat_p521_uint128)(arg1[8]) * ((arg2[4]) * 0x2));
  x6 = ((fiat_p521_uint128)(arg1[8]) * ((arg2[3]) * 0x2));
  x7 = ((fiat_p521_uint128)(arg1[8]) * ((arg2[2]) * 0x2));
  x8 = ((fiat_p521_uint128)(arg1[8]) * ((arg2[1]) * 0x2));
  x9 = ((fiat_p521_uint128)(arg1[7]) * ((arg2[8]) * 0x2));
  x10 = ((fiat_p521_uint128)(arg1[7]) * ((arg2[7]) * 0x2));
  x11 = ((fiat_p521_uint128)(arg1[7]) * ((arg2[6]) * 0x2));
  x12 = ((fiat_p521_uint128)(arg1[7]) * ((arg2[5]) * 0x2));
  x13 = ((fiat_p521_uint128)(arg1[7]) * ((arg2[4]) * 0x2));
  x14 = ((fiat_p521_uint128)(arg1[7]) * ((arg2[3]) * 0x2));
  x15 = ((fiat_p521_uint128)(arg1[7]) * ((arg2[2]) * 0x2));
  x16 = ((fiat_p521_uint128)(arg1[6]) * ((arg2[8]) * 0x2));
  x17 = ((fiat_p521_uint128)(arg1[6]) * ((arg2[7]) * 0x2));
  x18 = ((fiat_p521_uint128)(arg1[6]) * ((arg2[6]) * 0x2));
  x19 = ((fiat_p521_uint128)(arg1[6]) * ((arg2[5]) * 0x2));
  x20 = ((fiat_p521_uint128)(arg1[6]) * ((arg2[4]) * 0x2));
  x21 = ((fiat_p521_uint128)(arg1[6]) * ((arg2[3]) * 0x2));
  x22 = ((fiat_p521_uint128)(arg1[5]) * ((arg2[8]) * 0x2));
  x23 = ((fiat_p521_uint128)(arg1[5]) * ((arg2[7]) * 0x2));
  x24 = ((fiat_p521_uint128)(arg1[5]) * ((arg2[6]) * 0x2));
  x25 = ((fiat_p521_uint128)(arg1[5]) * ((arg2[5]) * 0x2));
  x26 = ((fiat_p521_uint128)(arg1[5]) * ((arg2[4]) * 0x2));
  x27 = ((fiat_p521_uint128)(arg1[4]) * ((arg2[8]) * 0x2));
  x28 = ((fiat_p521_uint128)(arg1[4]) * ((arg2[7]) * 0x2));
  x29 = ((fiat_p521_uint128)(arg1[4]) * ((arg2[6]) * 0x2));
  x30 = ((fiat_p521_uint128)(arg1[4]) * ((arg2[5]) * 0x2));
  x31 = ((fiat_p521_uint128)(arg1[3]) * ((arg2[8]) * 0x2));
  x32 = ((fiat_p521_uint128)(arg1[3]) * ((arg2[7]) * 0x2));
  x33 = ((fiat_p521_uint128)(arg1[3]) * ((arg2[6]) * 0x2));
  x34 = ((fiat_p521_uint128)(arg1[2]) * ((arg2[8]) * 0x2));
  x35 = ((fiat_p521_uint128)(arg1[2]) * ((arg2[7]) * 0x2));
  x36 = ((fiat_p521_uint128)(arg1[1]) * ((arg2[8]) * 0x2));
  x37 = ((fiat_p521_uint128)(arg1[8]) * (arg2[0]));
  x38 = ((fiat_p521_uint128)(arg1[7]) * (arg2[1]));
  x39 = ((fiat_p521_uint128)(arg1[7]) * (arg2[0]));
  x40 = ((fiat_p521_uint128)(arg1[6]) * (arg2[2]));
  x41 = ((fiat_p521_uint128)(arg1[6]) * (arg2[1]));
  x42 = ((fiat_p521_uint128)(arg1[6]) * (arg2[0]));
  x43 = ((fiat_p521_uint128)(arg1[5]) * (arg2[3]));
  x44 = ((fiat_p521_uint128)(arg1[5]) * (arg2[2]));
  x45 = ((fiat_p521_uint128)(arg1[5]) * (arg2[1]));
  x46 = ((fiat_p521_uint128)(arg1[5]) * (arg2[0]));
  x47 = ((fiat_p521_uint128)(arg1[4]) * (arg2[4]));
  x48 = ((fiat_p521_uint128)(arg1[4]) * (arg2[3]));
  x49 = ((fiat_p521_uint128)(arg1[4]) * (arg2[2]));
  x50 = ((fiat_p521_uint128)(arg1[4]) * (arg2[1]));
  x51 = ((fiat_p521_uint128)(arg1[4]) * (arg2[0]));
  x52 = ((fiat_p521_uint128)(arg1[3]) * (arg2[5]));
  x53 = ((fiat_p521_uint128)(arg1[3]) * (arg2[4]));
  x54 = ((fiat_p521_uint128)(arg1[3]) * (arg2[3]));
  x55 = ((fiat_p521_uint128)(arg1[3]) * (arg2[2]));
  x56 = ((fiat_p521_uint128)(arg1[3]) * (arg2[1]));
  x57 = ((fiat_p521_uint128)(arg1[3]) * (arg2[0]));
  x58 = ((fiat_p521_uint128)(arg1[2]) * (arg2[6]));
  x59 = ((fiat_p521_uint128)(arg1[2]) * (arg2[5]));
  x60 = ((fiat_p521_uint128)(arg1[2]) * (arg2[4]));
  x61 = ((fiat_p521_uint128)(arg1[2]) * (arg2[3]));
  x62 = ((fiat_p521_uint128)(arg1[2]) * (arg2[2]));
  x63 = ((fiat_p521_uint128)(arg1[2]) * (arg2[1]));
  x64 = ((fiat_p521_uint128)(arg1[2]) * (arg2[0]));
  x65 = ((fiat_p521_uint128)(arg1[1]) * (arg2[7]));
  x66 = ((fiat_p521_uint128)(arg1[1]) * (arg2[6]));
  x67 = ((fiat_p521_uint128)(arg1[1]) * (arg2[5]));
  x68 = ((fiat_p521_uint128)(arg1[1]) * (arg2[4]));
  x69 = ((fiat_p521_uint128)(arg1[1]) * (arg2[3]));
  x70 = ((fiat_p521_uint128)(arg1[1]) * (arg2[2]));
  x71 = ((fiat_p521_uint128)(arg1[1]) * (arg2[1]));
  x72 = ((fiat_p521_uint128)(arg1[1]) * (arg2[0]));
  x73 = ((fiat_p521_uint128)(arg1[0]) * (arg2[8]));
  x74 = ((fiat_p521_uint128)(arg1[0]) * (arg2[7]));
  x75 = ((fiat_p521_uint128)(arg1[0]) * (arg2[6]));
  x76 = ((fiat_p521_uint128)(arg1[0]) * (arg2[5]));
  x77 = ((fiat_p521_uint128)(arg1[0]) * (arg2[4]));
  x78 = ((fiat_p521_uint128)(arg1[0]) * (arg2[3]));
  x79 = ((fiat_p521_uint128)(arg1[0]) * (arg2[2]));
  x80 = ((fiat_p521_uint128)(arg1[0]) * (arg2[1]));
  x81 = ((fiat_p521_uint128)(arg1[0]) * (arg2[0]));
  x82 = (x81 + (x36 + (x35 + (x33 + (x30 + (x26 + (x21 + (x15 + x8))))))));
  x83 = (x82 >> 58);
  x84 = (uint64_t)(x82 & UINT64_C(0x3ffffffffffffff));
  x85 = (x73 + (x65 + (x58 + (x52 + (x47 + (x43 + (x40 + (x38 + x37))))))));
  x86 = (x74 + (x66 + (x59 + (x53 + (x48 + (x44 + (x41 + (x39 + x1))))))));
  x87 = (x75 + (x67 + (x60 + (x54 + (x49 + (x45 + (x42 + (x9 + x2))))))));
  x88 = (x76 + (x68 + (x61 + (x55 + (x50 + (x46 + (x16 + (x10 + x3))))))));
  x89 = (x77 + (x69 + (x62 + (x56 + (x51 + (x22 + (x17 + (x11 + x4))))))));
  x90 = (x78 + (x70 + (x63 + (x57 + (x27 + (x23 + (x18 + (x12 + x5))))))));
  x91 = (x79 + (x71 + (x64 + (x31 + (x28 + (x24 + (x19 + (x13 + x6))))))));
  x92 = (x80 + (x72 + (x34 + (x32 + (x29 + (x25 + (x20 + (x14 + x7))))))));
  x93 = (x83 + x92);
  x94 = (x93 >> 58);
  x95 = (uint64_t)(x93 & UINT64_C(0x3ffffffffffffff));
  x96 = (x94 + x91);
  x97 = (x96 >> 58);
  x98 = (uint64_t)(x96 & UINT64_C(0x3ffffffffffffff));
  x99 = (x97 + x90);
  x100 = (x99 >> 58);
  x101 = (uint64_t)(x99 & UINT64_C(0x3ffffffffffffff));
  x102 = (x100 + x89);
  x103 = (x102 >> 58);
  x104 = (uint64_t)(x102 & UINT64_C(0x3ffffffffffffff));
  x105 = (x103 + x88);
  x106 = (x105 >> 58);
  x107 = (uint64_t)(x105 & UINT64_C(0x3ffffffffffffff));
  x108 = (x106 + x87);
  x109 = (x108 >> 58);
  x110 = (uint64_t)(x108 & UINT64_C(0x3ffffffffffffff));
  x111 = (x109 + x86);
  x112 = (x111 >> 58);
  x113 = (uint64_t)(x111 & UINT64_C(0x3ffffffffffffff));
  x114 = (x112 + x85);
  x115 = (x114 >> 57);
  x116 = (uint64_t)(x114 & UINT64_C(0x1ffffffffffffff));
  x117 = (x84 + x115);
  x118 = (uint64_t)(x117 >> 58);
  x119 = (uint64_t)(x117 & UINT64_C(0x3ffffffffffffff));
  x120 = (x118 + x95);
  x121 = (fiat_p521_uint1)(x120 >> 58);
  x122 = (x120 & UINT64_C(0x3ffffffffffffff));
  x123 = (x121 + x98);
  out1[0] = x119;
  out1[1] = x122;
  out1[2] = x123;
  out1[3] = x101;
  out1[4] = x104;
  out1[5] = x107;
  out1[6] = x110;
  out1[7] = x113;
  out1[8] = x116;
}
