/* Autogenerated: '/home/sabrina/CryptOpt/dist/data/fiat-bridge/unsaturated_solinas' --lang C --inline-internal --internal-static --use-value-barrier p521 64 9 '2^521 - 1' carry_square */
/* curve description: p521 */
/* machine_wordsize = 64 (from "64") */
/* requested operations: carry_square */
/* n = 9 (from "9") */
/* s-c = 2^521 - [(1, 1)] (from "2^521 - 1") */
/* tight_bounds_multiplier = 1 (from "") */
/*  */
/* Computed values: */
/*   carry_chain = [0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1] */
/*   eval z = z[0] + (z[1] << 58) + (z[2] << 116) + (z[3] << 174) + (z[4] << 232) + (z[5] << 0x122) + (z[6] << 0x15c) + (z[7] << 0x196) + (z[8] << 0x1d0) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) + (z[32] << 256) + (z[33] << 0x108) + (z[34] << 0x110) + (z[35] << 0x118) + (z[36] << 0x120) + (z[37] << 0x128) + (z[38] << 0x130) + (z[39] << 0x138) + (z[40] << 0x140) + (z[41] << 0x148) + (z[42] << 0x150) + (z[43] << 0x158) + (z[44] << 0x160) + (z[45] << 0x168) + (z[46] << 0x170) + (z[47] << 0x178) + (z[48] << 0x180) + (z[49] << 0x188) + (z[50] << 0x190) + (z[51] << 0x198) + (z[52] << 0x1a0) + (z[53] << 0x1a8) + (z[54] << 0x1b0) + (z[55] << 0x1b8) + (z[56] << 0x1c0) + (z[57] << 0x1c8) + (z[58] << 0x1d0) + (z[59] << 0x1d8) + (z[60] << 0x1e0) + (z[61] << 0x1e8) + (z[62] << 0x1f0) + (z[63] << 0x1f8) + (z[64] << 2^9) + (z[65] << 0x208) */
/*   balance = [0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x3fffffffffffffe] */

#include <stdint.h>
typedef unsigned char fiat_p521_uint1;
typedef signed char fiat_p521_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_P521_FIAT_EXTENSION __extension__
#  define FIAT_P521_FIAT_INLINE __inline__
#else
#  define FIAT_P521_FIAT_EXTENSION
#  define FIAT_P521_FIAT_INLINE
#endif

FIAT_P521_FIAT_EXTENSION typedef signed __int128 fiat_p521_int128;
FIAT_P521_FIAT_EXTENSION typedef unsigned __int128 fiat_p521_uint128;

/* The type fiat_p521_loose_field_element is a field element with loose bounds. */
/* Bounds: [[0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0x600000000000000]] */
typedef uint64_t fiat_p521_loose_field_element[9];

/* The type fiat_p521_tight_field_element is a field element with tight bounds. */
/* Bounds: [[0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x200000000000000]] */
typedef uint64_t fiat_p521_tight_field_element[9];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif


/*
 * The function fiat_p521_carry_square squares a field element and reduces the result.
 *
 * Postconditions:
 *   eval out1 mod m = (eval arg1 * eval arg1) mod m
 *
 */
void fiat_p521_carry_square(fiat_p521_tight_field_element out1, const fiat_p521_loose_field_element arg1) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  uint64_t x14;
  uint64_t x15;
  uint64_t x16;
  fiat_p521_uint128 x17;
  fiat_p521_uint128 x18;
  fiat_p521_uint128 x19;
  fiat_p521_uint128 x20;
  fiat_p521_uint128 x21;
  fiat_p521_uint128 x22;
  fiat_p521_uint128 x23;
  fiat_p521_uint128 x24;
  fiat_p521_uint128 x25;
  fiat_p521_uint128 x26;
  fiat_p521_uint128 x27;
  fiat_p521_uint128 x28;
  fiat_p521_uint128 x29;
  fiat_p521_uint128 x30;
  fiat_p521_uint128 x31;
  fiat_p521_uint128 x32;
  fiat_p521_uint128 x33;
  fiat_p521_uint128 x34;
  fiat_p521_uint128 x35;
  fiat_p521_uint128 x36;
  fiat_p521_uint128 x37;
  fiat_p521_uint128 x38;
  fiat_p521_uint128 x39;
  fiat_p521_uint128 x40;
  fiat_p521_uint128 x41;
  fiat_p521_uint128 x42;
  fiat_p521_uint128 x43;
  fiat_p521_uint128 x44;
  fiat_p521_uint128 x45;
  fiat_p521_uint128 x46;
  fiat_p521_uint128 x47;
  fiat_p521_uint128 x48;
  fiat_p521_uint128 x49;
  fiat_p521_uint128 x50;
  fiat_p521_uint128 x51;
  fiat_p521_uint128 x52;
  fiat_p521_uint128 x53;
  fiat_p521_uint128 x54;
  fiat_p521_uint128 x55;
  fiat_p521_uint128 x56;
  fiat_p521_uint128 x57;
  fiat_p521_uint128 x58;
  fiat_p521_uint128 x59;
  fiat_p521_uint128 x60;
  fiat_p521_uint128 x61;
  fiat_p521_uint128 x62;
  fiat_p521_uint128 x63;
  uint64_t x64;
  fiat_p521_uint128 x65;
  fiat_p521_uint128 x66;
  fiat_p521_uint128 x67;
  fiat_p521_uint128 x68;
  fiat_p521_uint128 x69;
  fiat_p521_uint128 x70;
  fiat_p521_uint128 x71;
  fiat_p521_uint128 x72;
  fiat_p521_uint128 x73;
  fiat_p521_uint128 x74;
  uint64_t x75;
  fiat_p521_uint128 x76;
  fiat_p521_uint128 x77;
  uint64_t x78;
  fiat_p521_uint128 x79;
  fiat_p521_uint128 x80;
  uint64_t x81;
  fiat_p521_uint128 x82;
  fiat_p521_uint128 x83;
  uint64_t x84;
  fiat_p521_uint128 x85;
  fiat_p521_uint128 x86;
  uint64_t x87;
  fiat_p521_uint128 x88;
  fiat_p521_uint128 x89;
  uint64_t x90;
  fiat_p521_uint128 x91;
  fiat_p521_uint128 x92;
  uint64_t x93;
  fiat_p521_uint128 x94;
  fiat_p521_uint128 x95;
  uint64_t x96;
  fiat_p521_uint128 x97;
  uint64_t x98;
  uint64_t x99;
  uint64_t x100;
  fiat_p521_uint1 x101;
  uint64_t x102;
  uint64_t x103;
  x1 = (arg1[8]);
  x2 = (x1 * 0x2);
  x3 = ((arg1[8]) * 0x2);
  x4 = (arg1[7]);
  x5 = (x4 * 0x2);
  x6 = ((arg1[7]) * 0x2);
  x7 = (arg1[6]);
  x8 = (x7 * 0x2);
  x9 = ((arg1[6]) * 0x2);
  x10 = (arg1[5]);
  x11 = (x10 * 0x2);
  x12 = ((arg1[5]) * 0x2);
  x13 = ((arg1[4]) * 0x2);
  x14 = ((arg1[3]) * 0x2);
  x15 = ((arg1[2]) * 0x2);
  x16 = ((arg1[1]) * 0x2);
  x17 = ((fiat_p521_uint128)(arg1[8]) * (x1 * 0x2));
  x18 = ((fiat_p521_uint128)(arg1[7]) * (x2 * 0x2));
  x19 = ((fiat_p521_uint128)(arg1[7]) * (x4 * 0x2));
  x20 = ((fiat_p521_uint128)(arg1[6]) * (x2 * 0x2));
  x21 = ((fiat_p521_uint128)(arg1[6]) * (x5 * 0x2));
  x22 = ((fiat_p521_uint128)(arg1[6]) * (x7 * 0x2));
  x23 = ((fiat_p521_uint128)(arg1[5]) * (x2 * 0x2));
  x24 = ((fiat_p521_uint128)(arg1[5]) * (x5 * 0x2));
  x25 = ((fiat_p521_uint128)(arg1[5]) * (x8 * 0x2));
  x26 = ((fiat_p521_uint128)(arg1[5]) * (x10 * 0x2));
  x27 = ((fiat_p521_uint128)(arg1[4]) * (x2 * 0x2));
  x28 = ((fiat_p521_uint128)(arg1[4]) * (x5 * 0x2));
  x29 = ((fiat_p521_uint128)(arg1[4]) * (x8 * 0x2));
  x30 = ((fiat_p521_uint128)(arg1[4]) * (x11 * 0x2));
  x31 = ((fiat_p521_uint128)(arg1[4]) * (arg1[4]));
  x32 = ((fiat_p521_uint128)(arg1[3]) * (x2 * 0x2));
  x33 = ((fiat_p521_uint128)(arg1[3]) * (x5 * 0x2));
  x34 = ((fiat_p521_uint128)(arg1[3]) * (x8 * 0x2));
  x35 = ((fiat_p521_uint128)(arg1[3]) * x12);
  x36 = ((fiat_p521_uint128)(arg1[3]) * x13);
  x37 = ((fiat_p521_uint128)(arg1[3]) * (arg1[3]));
  x38 = ((fiat_p521_uint128)(arg1[2]) * (x2 * 0x2));
  x39 = ((fiat_p521_uint128)(arg1[2]) * (x5 * 0x2));
  x40 = ((fiat_p521_uint128)(arg1[2]) * x9);
  x41 = ((fiat_p521_uint128)(arg1[2]) * x12);
  x42 = ((fiat_p521_uint128)(arg1[2]) * x13);
  x43 = ((fiat_p521_uint128)(arg1[2]) * x14);
  x44 = ((fiat_p521_uint128)(arg1[2]) * (arg1[2]));
  x45 = ((fiat_p521_uint128)(arg1[1]) * (x2 * 0x2));
  x46 = ((fiat_p521_uint128)(arg1[1]) * x6);
  x47 = ((fiat_p521_uint128)(arg1[1]) * x9);
  x48 = ((fiat_p521_uint128)(arg1[1]) * x12);
  x49 = ((fiat_p521_uint128)(arg1[1]) * x13);
  x50 = ((fiat_p521_uint128)(arg1[1]) * x14);
  x51 = ((fiat_p521_uint128)(arg1[1]) * x15);
  x52 = ((fiat_p521_uint128)(arg1[1]) * (arg1[1]));
  x53 = ((fiat_p521_uint128)(arg1[0]) * x3);
  x54 = ((fiat_p521_uint128)(arg1[0]) * x6);
  x55 = ((fiat_p521_uint128)(arg1[0]) * x9);
  x56 = ((fiat_p521_uint128)(arg1[0]) * x12);
  x57 = ((fiat_p521_uint128)(arg1[0]) * x13);
  x58 = ((fiat_p521_uint128)(arg1[0]) * x14);
  x59 = ((fiat_p521_uint128)(arg1[0]) * x15);
  x60 = ((fiat_p521_uint128)(arg1[0]) * x16);
  x61 = ((fiat_p521_uint128)(arg1[0]) * (arg1[0]));
  x62 = (x61 + (x45 + (x39 + (x34 + x30))));
  x63 = (x62 >> 58);
  x64 = (uint64_t)(x62 & UINT64_C(0x3ffffffffffffff));
  x65 = (x53 + (x46 + (x40 + (x35 + x31))));
  x66 = (x54 + (x47 + (x41 + (x36 + x17))));
  x67 = (x55 + (x48 + (x42 + (x37 + x18))));
  x68 = (x56 + (x49 + (x43 + (x20 + x19))));
  x69 = (x57 + (x50 + (x44 + (x23 + x21))));
  x70 = (x58 + (x51 + (x27 + (x24 + x22))));
  x71 = (x59 + (x52 + (x32 + (x28 + x25))));
  x72 = (x60 + (x38 + (x33 + (x29 + x26))));
  x73 = (x63 + x72);
  x74 = (x73 >> 58);
  x75 = (uint64_t)(x73 & UINT64_C(0x3ffffffffffffff));
  x76 = (x74 + x71);
  x77 = (x76 >> 58);
  x78 = (uint64_t)(x76 & UINT64_C(0x3ffffffffffffff));
  x79 = (x77 + x70);
  x80 = (x79 >> 58);
  x81 = (uint64_t)(x79 & UINT64_C(0x3ffffffffffffff));
  x82 = (x80 + x69);
  x83 = (x82 >> 58);
  x84 = (uint64_t)(x82 & UINT64_C(0x3ffffffffffffff));
  x85 = (x83 + x68);
  x86 = (x85 >> 58);
  x87 = (uint64_t)(x85 & UINT64_C(0x3ffffffffffffff));
  x88 = (x86 + x67);
  x89 = (x88 >> 58);
  x90 = (uint64_t)(x88 & UINT64_C(0x3ffffffffffffff));
  x91 = (x89 + x66);
  x92 = (x91 >> 58);
  x93 = (uint64_t)(x91 & UINT64_C(0x3ffffffffffffff));
  x94 = (x92 + x65);
  x95 = (x94 >> 57);
  x96 = (uint64_t)(x94 & UINT64_C(0x1ffffffffffffff));
  x97 = (x64 + x95);
  x98 = (uint64_t)(x97 >> 58);
  x99 = (uint64_t)(x97 & UINT64_C(0x3ffffffffffffff));
  x100 = (x98 + x75);
  x101 = (fiat_p521_uint1)(x100 >> 58);
  x102 = (x100 & UINT64_C(0x3ffffffffffffff));
  x103 = (x101 + x78);
  out1[0] = x99;
  out1[1] = x102;
  out1[2] = x103;
  out1[3] = x81;
  out1[4] = x84;
  out1[5] = x87;
  out1[6] = x90;
  out1[7] = x93;
  out1[8] = x96;
}
