/* Autogenerated: '/home/sabrina/CryptOpt/dist/data/fiat-bridge/word_by_word_montgomery' --lang C --inline-internal --internal-static --use-value-barrier secp256k1_montgomery 64 '2^256 - 2^32 - 977' square */
/* curve description: secp256k1_montgomery */
/* machine_wordsize = 64 (from "64") */
/* requested operations: square */
/* m = 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f (from "2^256 - 2^32 - 977") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (m), and also   */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */
/*  */
/* Computed values: */
/*   eval z = z[0] + (z[1] << 64) + (z[2] << 128) + (z[3] << 192) */
/*   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) */
/*   twos_complement_eval z = let x1 := z[0] + (z[1] << 64) + (z[2] << 128) + (z[3] << 192) in */
/*                            if x1 & (2^256-1) < 2^255 then x1 & (2^256-1) else (x1 & (2^256-1)) - 2^256 */

#include <stdint.h>
typedef unsigned char fiat_secp256k1_montgomery_uint1;
typedef signed char fiat_secp256k1_montgomery_int1;
#if defined(__GNUC__) || defined(__clang__)
#  define FIAT_SECP256K1_MONTGOMERY_FIAT_EXTENSION __extension__
#  define FIAT_SECP256K1_MONTGOMERY_FIAT_INLINE __inline__
#else
#  define FIAT_SECP256K1_MONTGOMERY_FIAT_EXTENSION
#  define FIAT_SECP256K1_MONTGOMERY_FIAT_INLINE
#endif

FIAT_SECP256K1_MONTGOMERY_FIAT_EXTENSION typedef signed __int128 fiat_secp256k1_montgomery_int128;
FIAT_SECP256K1_MONTGOMERY_FIAT_EXTENSION typedef unsigned __int128 fiat_secp256k1_montgomery_uint128;

/* The type fiat_secp256k1_montgomery_montgomery_domain_field_element is a field element in the Montgomery domain. */
/* Bounds: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]] */
typedef uint64_t fiat_secp256k1_montgomery_montgomery_domain_field_element[4];

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif

#if !defined(FIAT_SECP256K1_MONTGOMERY_NO_ASM) && (defined(__GNUC__) || defined(__clang__))
static __inline__ uint64_t fiat_secp256k1_montgomery_value_barrier_u64(uint64_t a) {
  __asm__("" : "+r"(a) : /* no inputs */);
  return a;
}
#else
#  define fiat_secp256k1_montgomery_value_barrier_u64(x) (x)
#endif


/*
 * The function fiat_secp256k1_montgomery_addcarryx_u64 is an addition with carry.
 *
 * Postconditions:
 *   out1 = (arg1 + arg2 + arg3) mod 2^64
 *   out2 = ⌊(arg1 + arg2 + arg3) / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0x1]
 */
static FIAT_SECP256K1_MONTGOMERY_FIAT_INLINE void fiat_secp256k1_montgomery_addcarryx_u64(uint64_t* out1, fiat_secp256k1_montgomery_uint1* out2, fiat_secp256k1_montgomery_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_secp256k1_montgomery_uint128 x1;
  uint64_t x2;
  fiat_secp256k1_montgomery_uint1 x3;
  x1 = ((arg1 + (fiat_secp256k1_montgomery_uint128)arg2) + arg3);
  x2 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  x3 = (fiat_secp256k1_montgomery_uint1)(x1 >> 64);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_secp256k1_montgomery_subborrowx_u64 is a subtraction with borrow.
 *
 * Postconditions:
 *   out1 = (-arg1 + arg2 + -arg3) mod 2^64
 *   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0x1]
 */
static FIAT_SECP256K1_MONTGOMERY_FIAT_INLINE void fiat_secp256k1_montgomery_subborrowx_u64(uint64_t* out1, fiat_secp256k1_montgomery_uint1* out2, fiat_secp256k1_montgomery_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_secp256k1_montgomery_int128 x1;
  fiat_secp256k1_montgomery_int1 x2;
  uint64_t x3;
  x1 = ((arg2 - (fiat_secp256k1_montgomery_int128)arg1) - arg3);
  x2 = (fiat_secp256k1_montgomery_int1)(x1 >> 64);
  x3 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  *out1 = x3;
  *out2 = (fiat_secp256k1_montgomery_uint1)(0x0 - x2);
}

/*
 * The function fiat_secp256k1_montgomery_mulx_u64 is a multiplication, returning the full double-width result.
 *
 * Postconditions:
 *   out1 = (arg1 * arg2) mod 2^64
 *   out2 = ⌊arg1 * arg2 / 2^64⌋
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0xffffffffffffffff]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 *   out2: [0x0 ~> 0xffffffffffffffff]
 */
static FIAT_SECP256K1_MONTGOMERY_FIAT_INLINE void fiat_secp256k1_montgomery_mulx_u64(uint64_t* out1, uint64_t* out2, uint64_t arg1, uint64_t arg2) {
  fiat_secp256k1_montgomery_uint128 x1;
  uint64_t x2;
  uint64_t x3;
  x1 = ((fiat_secp256k1_montgomery_uint128)arg1 * arg2);
  x2 = (uint64_t)(x1 & UINT64_C(0xffffffffffffffff));
  x3 = (uint64_t)(x1 >> 64);
  *out1 = x2;
  *out2 = x3;
}

/*
 * The function fiat_secp256k1_montgomery_cmovznz_u64 is a single-word conditional move.
 *
 * Postconditions:
 *   out1 = (if arg1 = 0 then arg2 else arg3)
 *
 * Input Bounds:
 *   arg1: [0x0 ~> 0x1]
 *   arg2: [0x0 ~> 0xffffffffffffffff]
 *   arg3: [0x0 ~> 0xffffffffffffffff]
 * Output Bounds:
 *   out1: [0x0 ~> 0xffffffffffffffff]
 */
static FIAT_SECP256K1_MONTGOMERY_FIAT_INLINE void fiat_secp256k1_montgomery_cmovznz_u64(uint64_t* out1, fiat_secp256k1_montgomery_uint1 arg1, uint64_t arg2, uint64_t arg3) {
  fiat_secp256k1_montgomery_uint1 x1;
  uint64_t x2;
  uint64_t x3;
  x1 = (!(!arg1));
  x2 = ((fiat_secp256k1_montgomery_int1)(0x0 - x1) & UINT64_C(0xffffffffffffffff));
  x3 = ((fiat_secp256k1_montgomery_value_barrier_u64(x2) & arg3) | (fiat_secp256k1_montgomery_value_barrier_u64((~x2)) & arg2));
  *out1 = x3;
}

/*
 * The function fiat_secp256k1_montgomery_square squares a field element in the Montgomery domain.
 *
 * Preconditions:
 *   0 ≤ eval arg1 < m
 * Postconditions:
 *   eval (from_montgomery out1) mod m = (eval (from_montgomery arg1) * eval (from_montgomery arg1)) mod m
 *   0 ≤ eval out1 < m
 *
 */
void fiat_secp256k1_montgomery_square(fiat_secp256k1_montgomery_montgomery_domain_field_element out1, const fiat_secp256k1_montgomery_montgomery_domain_field_element arg1) {
  uint64_t x1;
  uint64_t x2;
  uint64_t x3;
  uint64_t x4;
  uint64_t x5;
  uint64_t x6;
  uint64_t x7;
  uint64_t x8;
  uint64_t x9;
  uint64_t x10;
  uint64_t x11;
  uint64_t x12;
  uint64_t x13;
  fiat_secp256k1_montgomery_uint1 x14;
  uint64_t x15;
  fiat_secp256k1_montgomery_uint1 x16;
  uint64_t x17;
  fiat_secp256k1_montgomery_uint1 x18;
  uint64_t x19;
  uint64_t x20;
  uint64_t x21;
  uint64_t x22;
  uint64_t x23;
  uint64_t x24;
  uint64_t x25;
  uint64_t x26;
  uint64_t x27;
  uint64_t x28;
  uint64_t x29;
  uint64_t x30;
  fiat_secp256k1_montgomery_uint1 x31;
  uint64_t x32;
  fiat_secp256k1_montgomery_uint1 x33;
  uint64_t x34;
  fiat_secp256k1_montgomery_uint1 x35;
  uint64_t x36;
  uint64_t x37;
  fiat_secp256k1_montgomery_uint1 x38;
  uint64_t x39;
  fiat_secp256k1_montgomery_uint1 x40;
  uint64_t x41;
  fiat_secp256k1_montgomery_uint1 x42;
  uint64_t x43;
  fiat_secp256k1_montgomery_uint1 x44;
  uint64_t x45;
  fiat_secp256k1_montgomery_uint1 x46;
  uint64_t x47;
  uint64_t x48;
  uint64_t x49;
  uint64_t x50;
  uint64_t x51;
  uint64_t x52;
  uint64_t x53;
  uint64_t x54;
  uint64_t x55;
  fiat_secp256k1_montgomery_uint1 x56;
  uint64_t x57;
  fiat_secp256k1_montgomery_uint1 x58;
  uint64_t x59;
  fiat_secp256k1_montgomery_uint1 x60;
  uint64_t x61;
  uint64_t x62;
  fiat_secp256k1_montgomery_uint1 x63;
  uint64_t x64;
  fiat_secp256k1_montgomery_uint1 x65;
  uint64_t x66;
  fiat_secp256k1_montgomery_uint1 x67;
  uint64_t x68;
  fiat_secp256k1_montgomery_uint1 x69;
  uint64_t x70;
  fiat_secp256k1_montgomery_uint1 x71;
  uint64_t x72;
  uint64_t x73;
  uint64_t x74;
  uint64_t x75;
  uint64_t x76;
  uint64_t x77;
  uint64_t x78;
  uint64_t x79;
  uint64_t x80;
  uint64_t x81;
  uint64_t x82;
  fiat_secp256k1_montgomery_uint1 x83;
  uint64_t x84;
  fiat_secp256k1_montgomery_uint1 x85;
  uint64_t x86;
  fiat_secp256k1_montgomery_uint1 x87;
  uint64_t x88;
  uint64_t x89;
  fiat_secp256k1_montgomery_uint1 x90;
  uint64_t x91;
  fiat_secp256k1_montgomery_uint1 x92;
  uint64_t x93;
  fiat_secp256k1_montgomery_uint1 x94;
  uint64_t x95;
  fiat_secp256k1_montgomery_uint1 x96;
  uint64_t x97;
  fiat_secp256k1_montgomery_uint1 x98;
  uint64_t x99;
  uint64_t x100;
  uint64_t x101;
  uint64_t x102;
  uint64_t x103;
  uint64_t x104;
  uint64_t x105;
  uint64_t x106;
  uint64_t x107;
  uint64_t x108;
  fiat_secp256k1_montgomery_uint1 x109;
  uint64_t x110;
  fiat_secp256k1_montgomery_uint1 x111;
  uint64_t x112;
  fiat_secp256k1_montgomery_uint1 x113;
  uint64_t x114;
  uint64_t x115;
  fiat_secp256k1_montgomery_uint1 x116;
  uint64_t x117;
  fiat_secp256k1_montgomery_uint1 x118;
  uint64_t x119;
  fiat_secp256k1_montgomery_uint1 x120;
  uint64_t x121;
  fiat_secp256k1_montgomery_uint1 x122;
  uint64_t x123;
  fiat_secp256k1_montgomery_uint1 x124;
  uint64_t x125;
  uint64_t x126;
  uint64_t x127;
  uint64_t x128;
  uint64_t x129;
  uint64_t x130;
  uint64_t x131;
  uint64_t x132;
  uint64_t x133;
  uint64_t x134;
  uint64_t x135;
  fiat_secp256k1_montgomery_uint1 x136;
  uint64_t x137;
  fiat_secp256k1_montgomery_uint1 x138;
  uint64_t x139;
  fiat_secp256k1_montgomery_uint1 x140;
  uint64_t x141;
  uint64_t x142;
  fiat_secp256k1_montgomery_uint1 x143;
  uint64_t x144;
  fiat_secp256k1_montgomery_uint1 x145;
  uint64_t x146;
  fiat_secp256k1_montgomery_uint1 x147;
  uint64_t x148;
  fiat_secp256k1_montgomery_uint1 x149;
  uint64_t x150;
  fiat_secp256k1_montgomery_uint1 x151;
  uint64_t x152;
  uint64_t x153;
  uint64_t x154;
  uint64_t x155;
  uint64_t x156;
  uint64_t x157;
  uint64_t x158;
  uint64_t x159;
  uint64_t x160;
  uint64_t x161;
  fiat_secp256k1_montgomery_uint1 x162;
  uint64_t x163;
  fiat_secp256k1_montgomery_uint1 x164;
  uint64_t x165;
  fiat_secp256k1_montgomery_uint1 x166;
  uint64_t x167;
  uint64_t x168;
  fiat_secp256k1_montgomery_uint1 x169;
  uint64_t x170;
  fiat_secp256k1_montgomery_uint1 x171;
  uint64_t x172;
  fiat_secp256k1_montgomery_uint1 x173;
  uint64_t x174;
  fiat_secp256k1_montgomery_uint1 x175;
  uint64_t x176;
  fiat_secp256k1_montgomery_uint1 x177;
  uint64_t x178;
  uint64_t x179;
  uint64_t x180;
  uint64_t x181;
  uint64_t x182;
  uint64_t x183;
  uint64_t x184;
  uint64_t x185;
  uint64_t x186;
  uint64_t x187;
  uint64_t x188;
  fiat_secp256k1_montgomery_uint1 x189;
  uint64_t x190;
  fiat_secp256k1_montgomery_uint1 x191;
  uint64_t x192;
  fiat_secp256k1_montgomery_uint1 x193;
  uint64_t x194;
  uint64_t x195;
  fiat_secp256k1_montgomery_uint1 x196;
  uint64_t x197;
  fiat_secp256k1_montgomery_uint1 x198;
  uint64_t x199;
  fiat_secp256k1_montgomery_uint1 x200;
  uint64_t x201;
  fiat_secp256k1_montgomery_uint1 x202;
  uint64_t x203;
  fiat_secp256k1_montgomery_uint1 x204;
  uint64_t x205;
  uint64_t x206;
  fiat_secp256k1_montgomery_uint1 x207;
  uint64_t x208;
  fiat_secp256k1_montgomery_uint1 x209;
  uint64_t x210;
  fiat_secp256k1_montgomery_uint1 x211;
  uint64_t x212;
  fiat_secp256k1_montgomery_uint1 x213;
  uint64_t x214;
  fiat_secp256k1_montgomery_uint1 x215;
  uint64_t x216;
  uint64_t x217;
  uint64_t x218;
  uint64_t x219;
  x1 = (arg1[1]);
  x2 = (arg1[2]);
  x3 = (arg1[3]);
  x4 = (arg1[0]);
  fiat_secp256k1_montgomery_mulx_u64(&x5, &x6, x4, (arg1[3]));
  fiat_secp256k1_montgomery_mulx_u64(&x7, &x8, x4, (arg1[2]));
  fiat_secp256k1_montgomery_mulx_u64(&x9, &x10, x4, (arg1[1]));
  fiat_secp256k1_montgomery_mulx_u64(&x11, &x12, x4, (arg1[0]));
  fiat_secp256k1_montgomery_addcarryx_u64(&x13, &x14, 0x0, x12, x9);
  fiat_secp256k1_montgomery_addcarryx_u64(&x15, &x16, x14, x10, x7);
  fiat_secp256k1_montgomery_addcarryx_u64(&x17, &x18, x16, x8, x5);
  x19 = (x18 + x6);
  fiat_secp256k1_montgomery_mulx_u64(&x20, &x21, x11, UINT64_C(0xd838091dd2253531));
  fiat_secp256k1_montgomery_mulx_u64(&x22, &x23, x20, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x24, &x25, x20, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x26, &x27, x20, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x28, &x29, x20, UINT64_C(0xfffffffefffffc2f));
  fiat_secp256k1_montgomery_addcarryx_u64(&x30, &x31, 0x0, x29, x26);
  fiat_secp256k1_montgomery_addcarryx_u64(&x32, &x33, x31, x27, x24);
  fiat_secp256k1_montgomery_addcarryx_u64(&x34, &x35, x33, x25, x22);
  x36 = (x35 + x23);
  fiat_secp256k1_montgomery_addcarryx_u64(&x37, &x38, 0x0, x11, x28);
  fiat_secp256k1_montgomery_addcarryx_u64(&x39, &x40, x38, x13, x30);
  fiat_secp256k1_montgomery_addcarryx_u64(&x41, &x42, x40, x15, x32);
  fiat_secp256k1_montgomery_addcarryx_u64(&x43, &x44, x42, x17, x34);
  fiat_secp256k1_montgomery_addcarryx_u64(&x45, &x46, x44, x19, x36);
  fiat_secp256k1_montgomery_mulx_u64(&x47, &x48, x1, (arg1[3]));
  fiat_secp256k1_montgomery_mulx_u64(&x49, &x50, x1, (arg1[2]));
  fiat_secp256k1_montgomery_mulx_u64(&x51, &x52, x1, (arg1[1]));
  fiat_secp256k1_montgomery_mulx_u64(&x53, &x54, x1, (arg1[0]));
  fiat_secp256k1_montgomery_addcarryx_u64(&x55, &x56, 0x0, x54, x51);
  fiat_secp256k1_montgomery_addcarryx_u64(&x57, &x58, x56, x52, x49);
  fiat_secp256k1_montgomery_addcarryx_u64(&x59, &x60, x58, x50, x47);
  x61 = (x60 + x48);
  fiat_secp256k1_montgomery_addcarryx_u64(&x62, &x63, 0x0, x39, x53);
  fiat_secp256k1_montgomery_addcarryx_u64(&x64, &x65, x63, x41, x55);
  fiat_secp256k1_montgomery_addcarryx_u64(&x66, &x67, x65, x43, x57);
  fiat_secp256k1_montgomery_addcarryx_u64(&x68, &x69, x67, x45, x59);
  fiat_secp256k1_montgomery_addcarryx_u64(&x70, &x71, x69, x46, x61);
  fiat_secp256k1_montgomery_mulx_u64(&x72, &x73, x62, UINT64_C(0xd838091dd2253531));
  fiat_secp256k1_montgomery_mulx_u64(&x74, &x75, x72, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x76, &x77, x72, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x78, &x79, x72, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x80, &x81, x72, UINT64_C(0xfffffffefffffc2f));
  fiat_secp256k1_montgomery_addcarryx_u64(&x82, &x83, 0x0, x81, x78);
  fiat_secp256k1_montgomery_addcarryx_u64(&x84, &x85, x83, x79, x76);
  fiat_secp256k1_montgomery_addcarryx_u64(&x86, &x87, x85, x77, x74);
  x88 = (x87 + x75);
  fiat_secp256k1_montgomery_addcarryx_u64(&x89, &x90, 0x0, x62, x80);
  fiat_secp256k1_montgomery_addcarryx_u64(&x91, &x92, x90, x64, x82);
  fiat_secp256k1_montgomery_addcarryx_u64(&x93, &x94, x92, x66, x84);
  fiat_secp256k1_montgomery_addcarryx_u64(&x95, &x96, x94, x68, x86);
  fiat_secp256k1_montgomery_addcarryx_u64(&x97, &x98, x96, x70, x88);
  x99 = ((uint64_t)x98 + x71);
  fiat_secp256k1_montgomery_mulx_u64(&x100, &x101, x2, (arg1[3]));
  fiat_secp256k1_montgomery_mulx_u64(&x102, &x103, x2, (arg1[2]));
  fiat_secp256k1_montgomery_mulx_u64(&x104, &x105, x2, (arg1[1]));
  fiat_secp256k1_montgomery_mulx_u64(&x106, &x107, x2, (arg1[0]));
  fiat_secp256k1_montgomery_addcarryx_u64(&x108, &x109, 0x0, x107, x104);
  fiat_secp256k1_montgomery_addcarryx_u64(&x110, &x111, x109, x105, x102);
  fiat_secp256k1_montgomery_addcarryx_u64(&x112, &x113, x111, x103, x100);
  x114 = (x113 + x101);
  fiat_secp256k1_montgomery_addcarryx_u64(&x115, &x116, 0x0, x91, x106);
  fiat_secp256k1_montgomery_addcarryx_u64(&x117, &x118, x116, x93, x108);
  fiat_secp256k1_montgomery_addcarryx_u64(&x119, &x120, x118, x95, x110);
  fiat_secp256k1_montgomery_addcarryx_u64(&x121, &x122, x120, x97, x112);
  fiat_secp256k1_montgomery_addcarryx_u64(&x123, &x124, x122, x99, x114);
  fiat_secp256k1_montgomery_mulx_u64(&x125, &x126, x115, UINT64_C(0xd838091dd2253531));
  fiat_secp256k1_montgomery_mulx_u64(&x127, &x128, x125, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x129, &x130, x125, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x131, &x132, x125, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x133, &x134, x125, UINT64_C(0xfffffffefffffc2f));
  fiat_secp256k1_montgomery_addcarryx_u64(&x135, &x136, 0x0, x134, x131);
  fiat_secp256k1_montgomery_addcarryx_u64(&x137, &x138, x136, x132, x129);
  fiat_secp256k1_montgomery_addcarryx_u64(&x139, &x140, x138, x130, x127);
  x141 = (x140 + x128);
  fiat_secp256k1_montgomery_addcarryx_u64(&x142, &x143, 0x0, x115, x133);
  fiat_secp256k1_montgomery_addcarryx_u64(&x144, &x145, x143, x117, x135);
  fiat_secp256k1_montgomery_addcarryx_u64(&x146, &x147, x145, x119, x137);
  fiat_secp256k1_montgomery_addcarryx_u64(&x148, &x149, x147, x121, x139);
  fiat_secp256k1_montgomery_addcarryx_u64(&x150, &x151, x149, x123, x141);
  x152 = ((uint64_t)x151 + x124);
  fiat_secp256k1_montgomery_mulx_u64(&x153, &x154, x3, (arg1[3]));
  fiat_secp256k1_montgomery_mulx_u64(&x155, &x156, x3, (arg1[2]));
  fiat_secp256k1_montgomery_mulx_u64(&x157, &x158, x3, (arg1[1]));
  fiat_secp256k1_montgomery_mulx_u64(&x159, &x160, x3, (arg1[0]));
  fiat_secp256k1_montgomery_addcarryx_u64(&x161, &x162, 0x0, x160, x157);
  fiat_secp256k1_montgomery_addcarryx_u64(&x163, &x164, x162, x158, x155);
  fiat_secp256k1_montgomery_addcarryx_u64(&x165, &x166, x164, x156, x153);
  x167 = (x166 + x154);
  fiat_secp256k1_montgomery_addcarryx_u64(&x168, &x169, 0x0, x144, x159);
  fiat_secp256k1_montgomery_addcarryx_u64(&x170, &x171, x169, x146, x161);
  fiat_secp256k1_montgomery_addcarryx_u64(&x172, &x173, x171, x148, x163);
  fiat_secp256k1_montgomery_addcarryx_u64(&x174, &x175, x173, x150, x165);
  fiat_secp256k1_montgomery_addcarryx_u64(&x176, &x177, x175, x152, x167);
  fiat_secp256k1_montgomery_mulx_u64(&x178, &x179, x168, UINT64_C(0xd838091dd2253531));
  fiat_secp256k1_montgomery_mulx_u64(&x180, &x181, x178, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x182, &x183, x178, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x184, &x185, x178, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_mulx_u64(&x186, &x187, x178, UINT64_C(0xfffffffefffffc2f));
  fiat_secp256k1_montgomery_addcarryx_u64(&x188, &x189, 0x0, x187, x184);
  fiat_secp256k1_montgomery_addcarryx_u64(&x190, &x191, x189, x185, x182);
  fiat_secp256k1_montgomery_addcarryx_u64(&x192, &x193, x191, x183, x180);
  x194 = (x193 + x181);
  fiat_secp256k1_montgomery_addcarryx_u64(&x195, &x196, 0x0, x168, x186);
  fiat_secp256k1_montgomery_addcarryx_u64(&x197, &x198, x196, x170, x188);
  fiat_secp256k1_montgomery_addcarryx_u64(&x199, &x200, x198, x172, x190);
  fiat_secp256k1_montgomery_addcarryx_u64(&x201, &x202, x200, x174, x192);
  fiat_secp256k1_montgomery_addcarryx_u64(&x203, &x204, x202, x176, x194);
  x205 = ((uint64_t)x204 + x177);
  fiat_secp256k1_montgomery_subborrowx_u64(&x206, &x207, 0x0, x197, UINT64_C(0xfffffffefffffc2f));
  fiat_secp256k1_montgomery_subborrowx_u64(&x208, &x209, x207, x199, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_subborrowx_u64(&x210, &x211, x209, x201, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_subborrowx_u64(&x212, &x213, x211, x203, UINT64_C(0xffffffffffffffff));
  fiat_secp256k1_montgomery_subborrowx_u64(&x214, &x215, x213, x205, 0x0);
  fiat_secp256k1_montgomery_cmovznz_u64(&x216, x215, x206, x197);
  fiat_secp256k1_montgomery_cmovznz_u64(&x217, x215, x208, x199);
  fiat_secp256k1_montgomery_cmovznz_u64(&x218, x215, x210, x201);
  fiat_secp256k1_montgomery_cmovznz_u64(&x219, x215, x212, x203);
  out1[0] = x216;
  out1[1] = x217;
  out1[2] = x218;
  out1[3] = x219;
}
