/* AUTO-GENERATED by keccak_gen.py — do not edit. */
/* Keccak-f[1600] full 24-round permutation, looped. 101 triads. */
/* loop_top = U7c68 (after 26-triad prologue). */
#define KECCAK_PERM_TRIADS 101
#define KECCAK_BUFLEN 56
#define KECCAK_BASE_LANE 16
#define KECCAK_COUNTER_LANE 30
#define KECCAK_RCTAB_LANE 32
