/* AUTO-GENERATED by keccak_gen.py — do not edit. */
/* Single Keccak round (round 0, RC=1). 108 triads. */
/* Buffer g_keccak_buf[30]; base RCX = &g_keccak_buf[14]. */
#define KECCAK_ROUND_TRIADS 108
#define KECCAK_BUFLEN 30
#define KECCAK_BASE_LANE 14
